/**
 * This file is generated by hand in order to bootstrap compiler development. It is intended to be an exact match to
 * compiled output.
 */

import * as capnp from "../index";
import { ObjectSize as __O, Struct as __S, Interface as __I } from '../index';
export const _capnpFileId = "b8630836983feed7";
export class Persistent_SaveParams extends __S {
    static readonly _capnp = { displayName: "SaveParams", id: "f76fba59183073a5", size: new __O(0, 1) };
    adoptSealFor(value: capnp.Orphan<capnp.Pointer>): void { __S.adopt(value, __S.getPointer(0, this)); }
    disownSealFor(): capnp.Orphan<capnp.Pointer> { return __S.disown(this.getSealFor()); }
    getSealFor(): capnp.Pointer { return __S.getPointer(0, this); }
    hasSealFor(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    setSealFor(value: capnp.Pointer): void { __S.copyFrom(value, __S.getPointer(0, this)); }
    toString(): string { return "Persistent_SaveParams_" + super.toString(); }
}
export class Persistent_SaveResults extends __S {
    static readonly _capnp = { displayName: "SaveResults", id: "b76848c18c40efbf", size: new __O(0, 1) };
    adoptSturdyRef(value: capnp.Orphan<capnp.Pointer>): void { __S.adopt(value, __S.getPointer(0, this)); }
    disownSturdyRef(): capnp.Orphan<capnp.Pointer> { return __S.disown(this.getSturdyRef()); }
    getSturdyRef(): capnp.Pointer { return __S.getPointer(0, this); }
    hasSturdyRef(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    setSturdyRef(value: capnp.Pointer): void { __S.copyFrom(value, __S.getPointer(0, this)); }
    toString(): string { return "Persistent_SaveResults_" + super.toString(); }
}
export class Persistent$Client {
    client: capnp.Client;
    constructor(client: capnp.Client) {
        this.client = client;
    }
    save(): void {
    }
}
export class Persistent$Server {
    save(): void {
    }
}
export class Persistent extends __I {
    static readonly SaveParams = Persistent_SaveParams;
    static readonly SaveResults = Persistent_SaveResults;
    static readonly Client = Persistent$Client;
    static readonly Server = Persistent$Server;
    static readonly _capnp = { displayName: "Persistent", id: "c8cb212fcd9f5691", size: new __O(0, 0) };
    toString(): string { return "Persistent_" + super.toString(); }
}
export class RealmGateway_Import$Params extends __S {
    static readonly _capnp = { displayName: "import$Params", id: "f0c2cc1d3909574d", size: new __O(0, 2) };
    getCap(): Persistent { return __S.getPointerAs(0, Persistent, this); }
    setCap(value: Persistent): void { __S.copyFrom(value, __S.getPointer(0, this)); }
    adoptParams(value: capnp.Orphan<Persistent_SaveParams>): void { __S.adopt(value, __S.getPointer(1, this)); }
    disownParams(): capnp.Orphan<Persistent_SaveParams> { return __S.disown(this.getParams()); }
    getParams(): Persistent_SaveParams { return __S.getStruct(1, Persistent_SaveParams, this); }
    hasParams(): boolean { return !__S.isNull(__S.getPointer(1, this)); }
    initParams(): Persistent_SaveParams { return __S.initStructAt(1, Persistent_SaveParams, this); }
    setParams(value: Persistent_SaveParams): void { __S.copyFrom(value, __S.getPointer(1, this)); }
    toString(): string { return "RealmGateway_Import$Params_" + super.toString(); }
}
export class RealmGateway_Export$Params extends __S {
    static readonly _capnp = { displayName: "export$Params", id: "ecafa18b482da3aa", size: new __O(0, 2) };
    getCap(): Persistent { return __S.getPointerAs(0, Persistent, this); }
    setCap(value: Persistent): void { __S.copyFrom(value, __S.getPointer(0, this)); }
    adoptParams(value: capnp.Orphan<Persistent_SaveParams>): void { __S.adopt(value, __S.getPointer(1, this)); }
    disownParams(): capnp.Orphan<Persistent_SaveParams> { return __S.disown(this.getParams()); }
    getParams(): Persistent_SaveParams { return __S.getStruct(1, Persistent_SaveParams, this); }
    hasParams(): boolean { return !__S.isNull(__S.getPointer(1, this)); }
    initParams(): Persistent_SaveParams { return __S.initStructAt(1, Persistent_SaveParams, this); }
    setParams(value: Persistent_SaveParams): void { __S.copyFrom(value, __S.getPointer(1, this)); }
    toString(): string { return "RealmGateway_Export$Params_" + super.toString(); }
}
export class RealmGateway$Client {
    client: capnp.Client;
    constructor(client: capnp.Client) {
        this.client = client;
    }
    import(): void {
    }
    export(): void {
    }
}
export class RealmGateway$Server {
    import(): void {
    }
    export(): void {
    }
}
export class RealmGateway extends __I {
    static readonly Client = RealmGateway$Client;
    static readonly Server = RealmGateway$Server;
    static readonly _capnp = { displayName: "RealmGateway", id: "84ff286cd00a3ed4", size: new __O(0, 0) };
    toString(): string { return "RealmGateway_" + super.toString(); }
}
