/* eslint-disable */

/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */

import * as capnp from "../index";
import { ObjectSize as __O, Struct as __S } from '../index';
export const _capnpFileId = BigInt("0xb8630836983feed7");
export interface Persistent_SaveParams_Shape {}
export interface Persistent_SaveParams_Json {}
export class Persistent_SaveParams<SturdyRef extends capnp.Struct = capnp.Struct, Owner extends capnp.Struct = capnp.Struct> extends __S {
    static readonly _capnp = { displayName: "SaveParams", id: "f76fba59183073a5", size: new __O(0, 1) };
    adoptSealFor(value: capnp.Orphan<capnp.Pointer>): void { __S.adopt(value, __S.getPointer(0, this)); }
    disownSealFor(): capnp.Orphan<capnp.Pointer> { return __S.disown(__S.getPointer(0, this)); }
    getSealFor<R extends capnp.Struct = Owner>(ctor?: capnp.StructCtor<R>): R { return __S.getStruct(0, capnp.getGenericBinding<R>(this, 1, ctor), this); }
    hasSealFor(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initSealFor<R extends capnp.Struct = Owner>(ctor?: capnp.StructCtor<R>): R { return __S.initStructAt(0, capnp.getGenericBinding<R>(this, 1, ctor), this); }
    setSealFor(value: Owner): void { __S.copyFrom(value, __S.getPointer(0, this)); }
    get sealFor(): Owner { return this.getSealFor(); }
    set sealFor(value: Owner) { this.setSealFor(value); }
    set(_value: Persistent_SaveParams_Shape): void { }
    get(): Persistent_SaveParams_Json { return {}; }
    toJSON(): Persistent_SaveParams_Json { return this.get(); }
    toString(): string { return "Persistent_SaveParams_" + super.toString(); }
}
export namespace Persistent_SaveParams {
    export type Json = Persistent_SaveParams_Json;
    export type Shape = Persistent_SaveParams_Shape;
}
export interface Persistent_SaveResults_Shape {}
export interface Persistent_SaveResults_Json {}
export class Persistent_SaveResults<SturdyRef extends capnp.Struct = capnp.Struct, Owner extends capnp.Struct = capnp.Struct> extends __S {
    static readonly _capnp = { displayName: "SaveResults", id: "b76848c18c40efbf", size: new __O(0, 1) };
    adoptSturdyRef(value: capnp.Orphan<capnp.Pointer>): void { __S.adopt(value, __S.getPointer(0, this)); }
    disownSturdyRef(): capnp.Orphan<capnp.Pointer> { return __S.disown(__S.getPointer(0, this)); }
    getSturdyRef<R extends capnp.Struct = SturdyRef>(ctor?: capnp.StructCtor<R>): R { return __S.getStruct(0, capnp.getGenericBinding<R>(this, 0, ctor), this); }
    hasSturdyRef(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initSturdyRef<R extends capnp.Struct = SturdyRef>(ctor?: capnp.StructCtor<R>): R { return __S.initStructAt(0, capnp.getGenericBinding<R>(this, 0, ctor), this); }
    setSturdyRef(value: SturdyRef): void { __S.copyFrom(value, __S.getPointer(0, this)); }
    get sturdyRef(): SturdyRef { return this.getSturdyRef(); }
    set sturdyRef(value: SturdyRef) { this.setSturdyRef(value); }
    set(_value: Persistent_SaveResults_Shape): void { }
    get(): Persistent_SaveResults_Json { return {}; }
    toJSON(): Persistent_SaveResults_Json { return this.get(); }
    toString(): string { return "Persistent_SaveResults_" + super.toString(); }
}
export namespace Persistent_SaveResults {
    export type Json = Persistent_SaveResults_Json;
    export type Shape = Persistent_SaveResults_Shape;
}
const Persistent_Methods: [
    capnp.Method<Persistent_SaveParams, Persistent_SaveResults>
] = [
    {
        interfaceId: BigInt("0xc8cb212fcd9f5691"),
        interfaceName: "capnp/persistent.capnp:Persistent",
        methodId: 0,
        methodName: "save",
        ParamsClass: Persistent_SaveParams,
        ResultsClass: Persistent_SaveResults,
    }
];
export class Persistent_Client<SturdyRef extends capnp.Struct = capnp.Struct, Owner extends capnp.Struct = capnp.Struct> {
    static readonly interfaceId: bigint = BigInt("0xc8cb212fcd9f5691");
    readonly bindings: [capnp.StructCtor<SturdyRef>, capnp.StructCtor<Owner>];
    readonly client: capnp.Client;
    readonly methods: [
        capnp.Method<Persistent_SaveParams<SturdyRef, Owner>, Persistent_SaveResults<SturdyRef, Owner>>
    ];
    constructor(client: capnp.Client, bindings: [capnp.StructCtor<SturdyRef>, capnp.StructCtor<Owner>]) {
        this.client = client;
        this.bindings = bindings;
        this.methods = [
            { ...Persistent_Methods[0], ParamsClass: capnp.bindGeneric(Persistent_SaveParams<SturdyRef, Owner>, bindings), ResultsClass: capnp.bindGeneric(Persistent_SaveResults<SturdyRef, Owner>, bindings) }
        ];
    }
    save(params?: ((params: Persistent_SaveParams<SturdyRef, Owner>) => void) | Persistent_SaveParams_Shape): capnp.RemotePromise<Persistent_SaveResults<SturdyRef, Owner>> { return this.client.call(this.methods[0], params); }
    dispose(): void { this.client.dispose(); }
    [Symbol.dispose](): void { this.client.dispose(); }
}
export interface Persistent_ServerTarget<SturdyRef extends capnp.Struct = capnp.Struct, Owner extends capnp.Struct = capnp.Struct> {
    save: capnp.ServerMethodImpl<Persistent_SaveParams<SturdyRef, Owner>, Persistent_SaveResults<SturdyRef, Owner>>;
}
export class Persistent_Server<SturdyRef extends capnp.Struct = capnp.Struct, Owner extends capnp.Struct = capnp.Struct> extends capnp.Server {
    constructor(target: Persistent_ServerTarget<SturdyRef, Owner>, bindings?: [capnp.StructCtor<SturdyRef>, capnp.StructCtor<Owner>]) {
        super([
            { ...Persistent_Methods[0], ...(bindings === undefined ? {} : { ParamsClass: capnp.bindGeneric(Persistent_SaveParams, bindings), ResultsClass: capnp.bindGeneric(Persistent_SaveResults, bindings) }), impl: target.save },
        ]);
    }
}
export type Persistent_Ref<SturdyRef extends capnp.Struct = capnp.Struct, Owner extends capnp.Struct = capnp.Struct> = Persistent_Client<SturdyRef, Owner> | Persistent_Server<SturdyRef, Owner>;
export class Persistent<SturdyRef extends capnp.Struct = capnp.Struct, Owner extends capnp.Struct = capnp.Struct> extends __S {
    static readonly _capnp = { displayName: "Persistent", id: "c8cb212fcd9f5691", size: new __O(0, 0) };
    toString(): string { return "Persistent_" + super.toString(); }
}
export namespace Persistent {
    export const Client = Persistent_Client;
    export type Client<SturdyRef extends capnp.Struct = capnp.Struct, Owner extends capnp.Struct = capnp.Struct> = Persistent_Client<SturdyRef, Owner>;
    export type Ref<SturdyRef extends capnp.Struct = capnp.Struct, Owner extends capnp.Struct = capnp.Struct> = Persistent_Ref<SturdyRef, Owner>;
    export import SaveParams = Persistent_SaveParams;
    export import SaveResults = Persistent_SaveResults;
    export const Server = Persistent_Server;
    export type Server<SturdyRef extends capnp.Struct = capnp.Struct, Owner extends capnp.Struct = capnp.Struct> = Persistent_Server<SturdyRef, Owner>;
}
