/* eslint-disable */

/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */

import * as capnp from "../index";
import { ObjectSize as __O, Struct as __S } from '../index';
export const _capnpFileId = BigInt("0xa184c7885cdaf2a1");
export enum Side {
    SERVER,
    CLIENT
}
export interface VatId_Shape {
    side?: Side;
}
export interface VatId_Json {
    side: Side;
}
export class VatId extends __S {
    static readonly _capnp = { displayName: "VatId", id: "d20b909fee733a8e", size: new __O(8, 0) };
    getSide(): Side { return __S.getUint16(0, this); }
    setSide(value: Side): void { __S.setUint16(0, value, this); }
    get side(): Side { return this.getSide(); }
    set side(value: Side) { this.setSide(value); }
    set(value: VatId_Shape): void {
        if (value.side !== undefined) this.setSide(value.side);
    }
    get(): VatId_Json {
        return {
            side: this.getSide(),
        };
    }
    toJSON(): VatId_Json { return this.get(); }
    toString(): string { return "VatId_" + super.toString(); }
}
export namespace VatId {
    export type Json = VatId_Json;
    export type Shape = VatId_Shape;
}
export interface ProvisionId_Shape {
    joinId?: number;
}
export interface ProvisionId_Json {
    joinId: number;
}
export class ProvisionId extends __S {
    static readonly _capnp = { displayName: "ProvisionId", id: "b88d09a9c5f39817", size: new __O(8, 0) };
    getJoinId(): number { return __S.getUint32(0, this); }
    setJoinId(value: number): void { __S.setUint32(0, value, this); }
    get joinId(): number { return this.getJoinId(); }
    set joinId(value: number) { this.setJoinId(value); }
    set(value: ProvisionId_Shape): void {
        if (value.joinId !== undefined) this.setJoinId(value.joinId);
    }
    get(): ProvisionId_Json {
        return {
            joinId: this.getJoinId(),
        };
    }
    toJSON(): ProvisionId_Json { return this.get(); }
    toString(): string { return "ProvisionId_" + super.toString(); }
}
export namespace ProvisionId {
    export type Json = ProvisionId_Json;
    export type Shape = ProvisionId_Shape;
}
export interface RecipientId_Shape {}
export interface RecipientId_Json {}
export class RecipientId extends __S {
    static readonly _capnp = { displayName: "RecipientId", id: "89f389b6fd4082c1", size: new __O(0, 0) };
    set(_value: RecipientId_Shape): void { }
    get(): RecipientId_Json { return {}; }
    toJSON(): RecipientId_Json { return this.get(); }
    toString(): string { return "RecipientId_" + super.toString(); }
}
export namespace RecipientId {
    export type Json = RecipientId_Json;
    export type Shape = RecipientId_Shape;
}
export interface ThirdPartyCapId_Shape {}
export interface ThirdPartyCapId_Json {}
export class ThirdPartyCapId extends __S {
    static readonly _capnp = { displayName: "ThirdPartyCapId", id: "b47f4979672cb59d", size: new __O(0, 0) };
    set(_value: ThirdPartyCapId_Shape): void { }
    get(): ThirdPartyCapId_Json { return {}; }
    toJSON(): ThirdPartyCapId_Json { return this.get(); }
    toString(): string { return "ThirdPartyCapId_" + super.toString(); }
}
export namespace ThirdPartyCapId {
    export type Json = ThirdPartyCapId_Json;
    export type Shape = ThirdPartyCapId_Shape;
}
export interface JoinKeyPart_Shape {
    joinId?: number;
    partCount?: number;
    partNum?: number;
}
export interface JoinKeyPart_Json {
    joinId: number;
    partCount: number;
    partNum: number;
}
export class JoinKeyPart extends __S {
    static readonly _capnp = { displayName: "JoinKeyPart", id: "95b29059097fca83", size: new __O(8, 0) };
    getJoinId(): number { return __S.getUint32(0, this); }
    setJoinId(value: number): void { __S.setUint32(0, value, this); }
    get joinId(): number { return this.getJoinId(); }
    set joinId(value: number) { this.setJoinId(value); }
    getPartCount(): number { return __S.getUint16(4, this); }
    setPartCount(value: number): void { __S.setUint16(4, value, this); }
    get partCount(): number { return this.getPartCount(); }
    set partCount(value: number) { this.setPartCount(value); }
    getPartNum(): number { return __S.getUint16(6, this); }
    setPartNum(value: number): void { __S.setUint16(6, value, this); }
    get partNum(): number { return this.getPartNum(); }
    set partNum(value: number) { this.setPartNum(value); }
    set(value: JoinKeyPart_Shape): void {
        if (value.joinId !== undefined) this.setJoinId(value.joinId);
        if (value.partCount !== undefined) this.setPartCount(value.partCount);
        if (value.partNum !== undefined) this.setPartNum(value.partNum);
    }
    get(): JoinKeyPart_Json {
        return {
            joinId: this.getJoinId(),
            partCount: this.getPartCount(),
            partNum: this.getPartNum(),
        };
    }
    toJSON(): JoinKeyPart_Json { return this.get(); }
    toString(): string { return "JoinKeyPart_" + super.toString(); }
}
export namespace JoinKeyPart {
    export type Json = JoinKeyPart_Json;
    export type Shape = JoinKeyPart_Shape;
}
export interface JoinResult_Shape {
    joinId?: number;
    succeeded?: boolean;
}
export interface JoinResult_Json {
    joinId: number;
    succeeded: boolean;
}
export class JoinResult extends __S {
    static readonly _capnp = { displayName: "JoinResult", id: "9d263a3630b7ebee", size: new __O(8, 1) };
    getJoinId(): number { return __S.getUint32(0, this); }
    setJoinId(value: number): void { __S.setUint32(0, value, this); }
    get joinId(): number { return this.getJoinId(); }
    set joinId(value: number) { this.setJoinId(value); }
    getSucceeded(): boolean { return __S.getBit(32, this); }
    setSucceeded(value: boolean): void { __S.setBit(32, value, this); }
    get succeeded(): boolean { return this.getSucceeded(); }
    set succeeded(value: boolean) { this.setSucceeded(value); }
    adoptCap(value: capnp.Orphan<capnp.Pointer>): void { __S.adopt(value, __S.getPointer(0, this)); }
    disownCap(): capnp.Orphan<capnp.Pointer> { return __S.disown(this.getCap()); }
    getCap(): capnp.Pointer { return __S.getPointer(0, this); }
    hasCap(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    setCap(value: capnp.Pointer): void { __S.copyFrom(value, __S.getPointer(0, this)); }
    get cap(): capnp.Pointer { return this.getCap(); }
    set cap(value: capnp.Pointer) { this.setCap(value); }
    set(value: JoinResult_Shape): void {
        if (value.joinId !== undefined) this.setJoinId(value.joinId);
        if (value.succeeded !== undefined) this.setSucceeded(value.succeeded);
    }
    get(): JoinResult_Json {
        return {
            joinId: this.getJoinId(),
            succeeded: this.getSucceeded(),
        };
    }
    toJSON(): JoinResult_Json { return this.get(); }
    toString(): string { return "JoinResult_" + super.toString(); }
}
export namespace JoinResult {
    export type Json = JoinResult_Json;
    export type Shape = JoinResult_Shape;
}
