/* eslint-disable */

/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */

import * as capnp from "../index";
import { ObjectSize as __O, Struct as __S } from '../index';
export const _capnpFileId = BigInt("0xb312981b2552a250");
export enum Message_Which {
    UNIMPLEMENTED = 0,
    ABORT = 1,
    BOOTSTRAP = 8,
    CALL = 2,
    RETURN = 3,
    FINISH = 4,
    RESOLVE = 5,
    RELEASE = 6,
    DISEMBARGO = 13,
    OBSOLETE_SAVE = 7,
    OBSOLETE_DELETE = 9,
    PROVIDE = 10,
    ACCEPT = 11,
    JOIN = 12
}
export interface Message_Shape {
    unimplemented?: Message_Shape;
    abort?: Exception_Shape;
    bootstrap?: Bootstrap_Shape;
    call?: Call_Shape;
    return?: Return_Shape;
    finish?: Finish_Shape;
    resolve?: Resolve_Shape;
    release?: Release_Shape;
    disembargo?: Disembargo_Shape;
    provide?: Provide_Shape;
    accept?: Accept_Shape;
    join?: Join_Shape;
}
export interface Message_Json {
    unimplemented?: Message_Json;
    abort?: Exception_Json;
    bootstrap?: Bootstrap_Json;
    call?: Call_Json;
    return?: Return_Json;
    finish?: Finish_Json;
    resolve?: Resolve_Json;
    release?: Release_Json;
    disembargo?: Disembargo_Json;
    provide?: Provide_Json;
    accept?: Accept_Json;
    join?: Join_Json;
}
export class Message extends __S {
    static readonly UNIMPLEMENTED = Message_Which.UNIMPLEMENTED;
    static readonly ABORT = Message_Which.ABORT;
    static readonly BOOTSTRAP = Message_Which.BOOTSTRAP;
    static readonly CALL = Message_Which.CALL;
    static readonly RETURN = Message_Which.RETURN;
    static readonly FINISH = Message_Which.FINISH;
    static readonly RESOLVE = Message_Which.RESOLVE;
    static readonly RELEASE = Message_Which.RELEASE;
    static readonly DISEMBARGO = Message_Which.DISEMBARGO;
    static readonly OBSOLETE_SAVE = Message_Which.OBSOLETE_SAVE;
    static readonly OBSOLETE_DELETE = Message_Which.OBSOLETE_DELETE;
    static readonly PROVIDE = Message_Which.PROVIDE;
    static readonly ACCEPT = Message_Which.ACCEPT;
    static readonly JOIN = Message_Which.JOIN;
    static readonly _capnp = { displayName: "Message", id: "91b79f1f808db032", size: new __O(8, 1) };
    adoptUnimplemented(value: capnp.Orphan<Message>): void {
        __S.setUint16(0, 0, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownUnimplemented(): capnp.Orphan<Message> { return __S.disown(this.getUnimplemented()); }
    getUnimplemented(): Message {
        __S.testWhich("unimplemented", __S.getUint16(0, this), 0, this);
        return __S.getStruct(0, Message, this);
    }
    hasUnimplemented(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initUnimplemented(): Message {
        __S.setUint16(0, 0, this);
        return __S.initStructAt(0, Message, this);
    }
    isUnimplemented(): boolean { return __S.getUint16(0, this) === 0; }
    setUnimplemented(value: Message): void {
        __S.setUint16(0, 0, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get unimplemented(): Message { return this.getUnimplemented(); }
    set unimplemented(value: Message | Message_Shape) { if (value instanceof Message) { this.setUnimplemented(value); } else { this.initUnimplemented().set(value); } }
    adoptAbort(value: capnp.Orphan<Exception>): void {
        __S.setUint16(0, 1, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownAbort(): capnp.Orphan<Exception> { return __S.disown(this.getAbort()); }
    getAbort(): Exception {
        __S.testWhich("abort", __S.getUint16(0, this), 1, this);
        return __S.getStruct(0, Exception, this);
    }
    hasAbort(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initAbort(): Exception {
        __S.setUint16(0, 1, this);
        return __S.initStructAt(0, Exception, this);
    }
    isAbort(): boolean { return __S.getUint16(0, this) === 1; }
    setAbort(value: Exception): void {
        __S.setUint16(0, 1, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get abort(): Exception { return this.getAbort(); }
    set abort(value: Exception | Exception_Shape) { if (value instanceof Exception) { this.setAbort(value); } else { this.initAbort().set(value); } }
    adoptBootstrap(value: capnp.Orphan<Bootstrap>): void {
        __S.setUint16(0, 8, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownBootstrap(): capnp.Orphan<Bootstrap> { return __S.disown(this.getBootstrap()); }
    getBootstrap(): Bootstrap {
        __S.testWhich("bootstrap", __S.getUint16(0, this), 8, this);
        return __S.getStruct(0, Bootstrap, this);
    }
    hasBootstrap(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initBootstrap(): Bootstrap {
        __S.setUint16(0, 8, this);
        return __S.initStructAt(0, Bootstrap, this);
    }
    isBootstrap(): boolean { return __S.getUint16(0, this) === 8; }
    setBootstrap(value: Bootstrap): void {
        __S.setUint16(0, 8, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get bootstrap(): Bootstrap { return this.getBootstrap(); }
    set bootstrap(value: Bootstrap | Bootstrap_Shape) { if (value instanceof Bootstrap) { this.setBootstrap(value); } else { this.initBootstrap().set(value); } }
    adoptCall(value: capnp.Orphan<Call>): void {
        __S.setUint16(0, 2, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownCall(): capnp.Orphan<Call> { return __S.disown(this.getCall()); }
    getCall(): Call {
        __S.testWhich("call", __S.getUint16(0, this), 2, this);
        return __S.getStruct(0, Call, this);
    }
    hasCall(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initCall(): Call {
        __S.setUint16(0, 2, this);
        return __S.initStructAt(0, Call, this);
    }
    isCall(): boolean { return __S.getUint16(0, this) === 2; }
    setCall(value: Call): void {
        __S.setUint16(0, 2, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get call(): Call { return this.getCall(); }
    set call(value: Call | Call_Shape) { if (value instanceof Call) { this.setCall(value); } else { this.initCall().set(value); } }
    adoptReturn(value: capnp.Orphan<Return>): void {
        __S.setUint16(0, 3, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownReturn(): capnp.Orphan<Return> { return __S.disown(this.getReturn()); }
    getReturn(): Return {
        __S.testWhich("return", __S.getUint16(0, this), 3, this);
        return __S.getStruct(0, Return, this);
    }
    hasReturn(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initReturn(): Return {
        __S.setUint16(0, 3, this);
        return __S.initStructAt(0, Return, this);
    }
    isReturn(): boolean { return __S.getUint16(0, this) === 3; }
    setReturn(value: Return): void {
        __S.setUint16(0, 3, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get return(): Return { return this.getReturn(); }
    set return(value: Return | Return_Shape) { if (value instanceof Return) { this.setReturn(value); } else { this.initReturn().set(value); } }
    adoptFinish(value: capnp.Orphan<Finish>): void {
        __S.setUint16(0, 4, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownFinish(): capnp.Orphan<Finish> { return __S.disown(this.getFinish()); }
    getFinish(): Finish {
        __S.testWhich("finish", __S.getUint16(0, this), 4, this);
        return __S.getStruct(0, Finish, this);
    }
    hasFinish(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initFinish(): Finish {
        __S.setUint16(0, 4, this);
        return __S.initStructAt(0, Finish, this);
    }
    isFinish(): boolean { return __S.getUint16(0, this) === 4; }
    setFinish(value: Finish): void {
        __S.setUint16(0, 4, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get finish(): Finish { return this.getFinish(); }
    set finish(value: Finish | Finish_Shape) { if (value instanceof Finish) { this.setFinish(value); } else { this.initFinish().set(value); } }
    adoptResolve(value: capnp.Orphan<Resolve>): void {
        __S.setUint16(0, 5, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownResolve(): capnp.Orphan<Resolve> { return __S.disown(this.getResolve()); }
    getResolve(): Resolve {
        __S.testWhich("resolve", __S.getUint16(0, this), 5, this);
        return __S.getStruct(0, Resolve, this);
    }
    hasResolve(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initResolve(): Resolve {
        __S.setUint16(0, 5, this);
        return __S.initStructAt(0, Resolve, this);
    }
    isResolve(): boolean { return __S.getUint16(0, this) === 5; }
    setResolve(value: Resolve): void {
        __S.setUint16(0, 5, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get resolve(): Resolve { return this.getResolve(); }
    set resolve(value: Resolve | Resolve_Shape) { if (value instanceof Resolve) { this.setResolve(value); } else { this.initResolve().set(value); } }
    adoptRelease(value: capnp.Orphan<Release>): void {
        __S.setUint16(0, 6, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownRelease(): capnp.Orphan<Release> { return __S.disown(this.getRelease()); }
    getRelease(): Release {
        __S.testWhich("release", __S.getUint16(0, this), 6, this);
        return __S.getStruct(0, Release, this);
    }
    hasRelease(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initRelease(): Release {
        __S.setUint16(0, 6, this);
        return __S.initStructAt(0, Release, this);
    }
    isRelease(): boolean { return __S.getUint16(0, this) === 6; }
    setRelease(value: Release): void {
        __S.setUint16(0, 6, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get release(): Release { return this.getRelease(); }
    set release(value: Release | Release_Shape) { if (value instanceof Release) { this.setRelease(value); } else { this.initRelease().set(value); } }
    adoptDisembargo(value: capnp.Orphan<Disembargo>): void {
        __S.setUint16(0, 13, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownDisembargo(): capnp.Orphan<Disembargo> { return __S.disown(this.getDisembargo()); }
    getDisembargo(): Disembargo {
        __S.testWhich("disembargo", __S.getUint16(0, this), 13, this);
        return __S.getStruct(0, Disembargo, this);
    }
    hasDisembargo(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initDisembargo(): Disembargo {
        __S.setUint16(0, 13, this);
        return __S.initStructAt(0, Disembargo, this);
    }
    isDisembargo(): boolean { return __S.getUint16(0, this) === 13; }
    setDisembargo(value: Disembargo): void {
        __S.setUint16(0, 13, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get disembargo(): Disembargo { return this.getDisembargo(); }
    set disembargo(value: Disembargo | Disembargo_Shape) { if (value instanceof Disembargo) { this.setDisembargo(value); } else { this.initDisembargo().set(value); } }
    adoptObsoleteSave(value: capnp.Orphan<capnp.Pointer>): void {
        __S.setUint16(0, 7, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownObsoleteSave(): capnp.Orphan<capnp.Pointer> { return __S.disown(this.getObsoleteSave()); }
    getObsoleteSave(): capnp.Pointer {
        __S.testWhich("obsoleteSave", __S.getUint16(0, this), 7, this);
        return __S.getPointer(0, this);
    }
    hasObsoleteSave(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    isObsoleteSave(): boolean { return __S.getUint16(0, this) === 7; }
    setObsoleteSave(value: capnp.Pointer): void {
        __S.setUint16(0, 7, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get obsoleteSave(): capnp.Pointer { return this.getObsoleteSave(); }
    set obsoleteSave(value: capnp.Pointer) { this.setObsoleteSave(value); }
    adoptObsoleteDelete(value: capnp.Orphan<capnp.Pointer>): void {
        __S.setUint16(0, 9, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownObsoleteDelete(): capnp.Orphan<capnp.Pointer> { return __S.disown(this.getObsoleteDelete()); }
    getObsoleteDelete(): capnp.Pointer {
        __S.testWhich("obsoleteDelete", __S.getUint16(0, this), 9, this);
        return __S.getPointer(0, this);
    }
    hasObsoleteDelete(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    isObsoleteDelete(): boolean { return __S.getUint16(0, this) === 9; }
    setObsoleteDelete(value: capnp.Pointer): void {
        __S.setUint16(0, 9, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get obsoleteDelete(): capnp.Pointer { return this.getObsoleteDelete(); }
    set obsoleteDelete(value: capnp.Pointer) { this.setObsoleteDelete(value); }
    adoptProvide(value: capnp.Orphan<Provide>): void {
        __S.setUint16(0, 10, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownProvide(): capnp.Orphan<Provide> { return __S.disown(this.getProvide()); }
    getProvide(): Provide {
        __S.testWhich("provide", __S.getUint16(0, this), 10, this);
        return __S.getStruct(0, Provide, this);
    }
    hasProvide(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initProvide(): Provide {
        __S.setUint16(0, 10, this);
        return __S.initStructAt(0, Provide, this);
    }
    isProvide(): boolean { return __S.getUint16(0, this) === 10; }
    setProvide(value: Provide): void {
        __S.setUint16(0, 10, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get provide(): Provide { return this.getProvide(); }
    set provide(value: Provide | Provide_Shape) { if (value instanceof Provide) { this.setProvide(value); } else { this.initProvide().set(value); } }
    adoptAccept(value: capnp.Orphan<Accept>): void {
        __S.setUint16(0, 11, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownAccept(): capnp.Orphan<Accept> { return __S.disown(this.getAccept()); }
    getAccept(): Accept {
        __S.testWhich("accept", __S.getUint16(0, this), 11, this);
        return __S.getStruct(0, Accept, this);
    }
    hasAccept(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initAccept(): Accept {
        __S.setUint16(0, 11, this);
        return __S.initStructAt(0, Accept, this);
    }
    isAccept(): boolean { return __S.getUint16(0, this) === 11; }
    setAccept(value: Accept): void {
        __S.setUint16(0, 11, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get accept(): Accept { return this.getAccept(); }
    set accept(value: Accept | Accept_Shape) { if (value instanceof Accept) { this.setAccept(value); } else { this.initAccept().set(value); } }
    adoptJoin(value: capnp.Orphan<Join>): void {
        __S.setUint16(0, 12, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownJoin(): capnp.Orphan<Join> { return __S.disown(this.getJoin()); }
    getJoin(): Join {
        __S.testWhich("join", __S.getUint16(0, this), 12, this);
        return __S.getStruct(0, Join, this);
    }
    hasJoin(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initJoin(): Join {
        __S.setUint16(0, 12, this);
        return __S.initStructAt(0, Join, this);
    }
    isJoin(): boolean { return __S.getUint16(0, this) === 12; }
    setJoin(value: Join): void {
        __S.setUint16(0, 12, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get join(): Join { return this.getJoin(); }
    set join(value: Join | Join_Shape) { if (value instanceof Join) { this.setJoin(value); } else { this.initJoin().set(value); } }
    set(value: Message_Shape): void {
        if (value.unimplemented !== undefined) this.initUnimplemented().set(value.unimplemented);
        if (value.abort !== undefined) this.initAbort().set(value.abort);
        if (value.bootstrap !== undefined) this.initBootstrap().set(value.bootstrap);
        if (value.call !== undefined) this.initCall().set(value.call);
        if (value.return !== undefined) this.initReturn().set(value.return);
        if (value.finish !== undefined) this.initFinish().set(value.finish);
        if (value.resolve !== undefined) this.initResolve().set(value.resolve);
        if (value.release !== undefined) this.initRelease().set(value.release);
        if (value.disembargo !== undefined) this.initDisembargo().set(value.disembargo);
        if (value.provide !== undefined) this.initProvide().set(value.provide);
        if (value.accept !== undefined) this.initAccept().set(value.accept);
        if (value.join !== undefined) this.initJoin().set(value.join);
    }
    get(): Message_Json {
        return {
            ...(this.isUnimplemented() && this.hasUnimplemented() ? { unimplemented: this.getUnimplemented().get() } : {}),
            ...(this.isAbort() && this.hasAbort() ? { abort: this.getAbort().get() } : {}),
            ...(this.isBootstrap() && this.hasBootstrap() ? { bootstrap: this.getBootstrap().get() } : {}),
            ...(this.isCall() && this.hasCall() ? { call: this.getCall().get() } : {}),
            ...(this.isReturn() && this.hasReturn() ? { return: this.getReturn().get() } : {}),
            ...(this.isFinish() && this.hasFinish() ? { finish: this.getFinish().get() } : {}),
            ...(this.isResolve() && this.hasResolve() ? { resolve: this.getResolve().get() } : {}),
            ...(this.isRelease() && this.hasRelease() ? { release: this.getRelease().get() } : {}),
            ...(this.isDisembargo() && this.hasDisembargo() ? { disembargo: this.getDisembargo().get() } : {}),
            ...(this.isProvide() && this.hasProvide() ? { provide: this.getProvide().get() } : {}),
            ...(this.isAccept() && this.hasAccept() ? { accept: this.getAccept().get() } : {}),
            ...(this.isJoin() && this.hasJoin() ? { join: this.getJoin().get() } : {}),
        };
    }
    toJSON(): Message_Json { return this.get(); }
    toString(): string { return "Message_" + super.toString(); }
    which(): Message_Which { return __S.getUint16(0, this); }
}
export namespace Message {
    export type Json = Message_Json;
    export type Shape = Message_Shape;
    export import Which = Message_Which;
}
export interface Bootstrap_Shape {
    questionId?: number;
}
export interface Bootstrap_Json {
    questionId: number;
}
export class Bootstrap extends __S {
    static readonly _capnp = { displayName: "Bootstrap", id: "e94ccf8031176ec4", size: new __O(8, 1) };
    getQuestionId(): number { return __S.getUint32(0, this); }
    setQuestionId(value: number): void { __S.setUint32(0, value, this); }
    get questionId(): number { return this.getQuestionId(); }
    set questionId(value: number) { this.setQuestionId(value); }
    adoptDeprecatedObjectId(value: capnp.Orphan<capnp.Pointer>): void { __S.adopt(value, __S.getPointer(0, this)); }
    disownDeprecatedObjectId(): capnp.Orphan<capnp.Pointer> { return __S.disown(this.getDeprecatedObjectId()); }
    getDeprecatedObjectId(): capnp.Pointer { return __S.getPointer(0, this); }
    hasDeprecatedObjectId(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    setDeprecatedObjectId(value: capnp.Pointer): void { __S.copyFrom(value, __S.getPointer(0, this)); }
    get deprecatedObjectId(): capnp.Pointer { return this.getDeprecatedObjectId(); }
    set deprecatedObjectId(value: capnp.Pointer) { this.setDeprecatedObjectId(value); }
    set(value: Bootstrap_Shape): void {
        if (value.questionId !== undefined) this.setQuestionId(value.questionId);
    }
    get(): Bootstrap_Json {
        return {
            questionId: this.getQuestionId(),
        };
    }
    toJSON(): Bootstrap_Json { return this.get(); }
    toString(): string { return "Bootstrap_" + super.toString(); }
}
export namespace Bootstrap {
    export type Json = Bootstrap_Json;
    export type Shape = Bootstrap_Shape;
}
export enum Call_SendResultsTo_Which {
    CALLER = 0,
    YOURSELF = 1,
    THIRD_PARTY = 2
}
export interface Call_SendResultsTo_Shape {
    caller?: null;
    yourself?: null;
}
export interface Call_SendResultsTo_Json {
    caller?: null;
    yourself?: null;
}
export class Call_SendResultsTo extends __S {
    static readonly CALLER = Call_SendResultsTo_Which.CALLER;
    static readonly YOURSELF = Call_SendResultsTo_Which.YOURSELF;
    static readonly THIRD_PARTY = Call_SendResultsTo_Which.THIRD_PARTY;
    static readonly _capnp = { displayName: "sendResultsTo", id: "dae8b0f61aab5f99", size: new __O(24, 3) };
    isCaller(): boolean { return __S.getUint16(6, this) === 0; }
    setCaller(): void { __S.setUint16(6, 0, this); }
    isYourself(): boolean { return __S.getUint16(6, this) === 1; }
    setYourself(): void { __S.setUint16(6, 1, this); }
    adoptThirdParty(value: capnp.Orphan<capnp.Pointer>): void {
        __S.setUint16(6, 2, this);
        __S.adopt(value, __S.getPointer(2, this));
    }
    disownThirdParty(): capnp.Orphan<capnp.Pointer> { return __S.disown(this.getThirdParty()); }
    getThirdParty(): capnp.Pointer {
        __S.testWhich("thirdParty", __S.getUint16(6, this), 2, this);
        return __S.getPointer(2, this);
    }
    hasThirdParty(): boolean { return !__S.isNull(__S.getPointer(2, this)); }
    isThirdParty(): boolean { return __S.getUint16(6, this) === 2; }
    setThirdParty(value: capnp.Pointer): void {
        __S.setUint16(6, 2, this);
        __S.copyFrom(value, __S.getPointer(2, this));
    }
    get thirdParty(): capnp.Pointer { return this.getThirdParty(); }
    set thirdParty(value: capnp.Pointer) { this.setThirdParty(value); }
    set(value: Call_SendResultsTo_Shape): void {
        if (value.caller !== undefined) this.setCaller();
        if (value.yourself !== undefined) this.setYourself();
    }
    get(): Call_SendResultsTo_Json {
        return {
            ...(this.isCaller() ? { caller: null } : {}),
            ...(this.isYourself() ? { yourself: null } : {}),
        };
    }
    toJSON(): Call_SendResultsTo_Json { return this.get(); }
    toString(): string { return "Call_SendResultsTo_" + super.toString(); }
    which(): Call_SendResultsTo_Which { return __S.getUint16(6, this); }
}
export namespace Call_SendResultsTo {
    export type Json = Call_SendResultsTo_Json;
    export type Shape = Call_SendResultsTo_Shape;
    export import Which = Call_SendResultsTo_Which;
}
export interface Call_Shape {
    questionId?: number;
    target?: MessageTarget_Shape;
    interfaceId?: bigint | number | string;
    methodId?: number;
    allowThirdPartyTailCall?: boolean;
    noPromisePipelining?: boolean;
    onlyPromisePipeline?: boolean;
    params?: Payload_Shape;
    sendResultsTo?: Call_SendResultsTo_Shape;
}
export interface Call_Json {
    questionId: number;
    target?: MessageTarget_Json;
    interfaceId: string;
    methodId: number;
    allowThirdPartyTailCall: boolean;
    noPromisePipelining: boolean;
    onlyPromisePipeline: boolean;
    params?: Payload_Json;
    sendResultsTo: Call_SendResultsTo_Json;
}
export class Call extends __S {
    static readonly _capnp = { displayName: "Call", id: "836a53ce789d4cd4", size: new __O(24, 3), defaultAllowThirdPartyTailCall: capnp.getBitMask(false, 0), defaultNoPromisePipelining: capnp.getBitMask(false, 1), defaultOnlyPromisePipeline: capnp.getBitMask(false, 2) };
    getQuestionId(): number { return __S.getUint32(0, this); }
    setQuestionId(value: number): void { __S.setUint32(0, value, this); }
    get questionId(): number { return this.getQuestionId(); }
    set questionId(value: number) { this.setQuestionId(value); }
    adoptTarget(value: capnp.Orphan<MessageTarget>): void { __S.adopt(value, __S.getPointer(0, this)); }
    disownTarget(): capnp.Orphan<MessageTarget> { return __S.disown(this.getTarget()); }
    getTarget(): MessageTarget { return __S.getStruct(0, MessageTarget, this); }
    hasTarget(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initTarget(): MessageTarget { return __S.initStructAt(0, MessageTarget, this); }
    setTarget(value: MessageTarget): void { __S.copyFrom(value, __S.getPointer(0, this)); }
    get target(): MessageTarget { return this.getTarget(); }
    set target(value: MessageTarget | MessageTarget_Shape) { if (value instanceof MessageTarget) { this.setTarget(value); } else { this.initTarget().set(value); } }
    getInterfaceId(): bigint { return __S.getUint64(8, this); }
    setInterfaceId(value: bigint): void { __S.setUint64(8, value, this); }
    get interfaceId(): bigint { return this.getInterfaceId(); }
    set interfaceId(value: bigint | number | string) { this.setInterfaceId(BigInt(value)); }
    getMethodId(): number { return __S.getUint16(4, this); }
    setMethodId(value: number): void { __S.setUint16(4, value, this); }
    get methodId(): number { return this.getMethodId(); }
    set methodId(value: number) { this.setMethodId(value); }
    getAllowThirdPartyTailCall(): boolean { return __S.getBit(128, this, Call._capnp.defaultAllowThirdPartyTailCall); }
    setAllowThirdPartyTailCall(value: boolean): void { __S.setBit(128, value, this, Call._capnp.defaultAllowThirdPartyTailCall); }
    get allowThirdPartyTailCall(): boolean { return this.getAllowThirdPartyTailCall(); }
    set allowThirdPartyTailCall(value: boolean) { this.setAllowThirdPartyTailCall(value); }
    getNoPromisePipelining(): boolean { return __S.getBit(129, this, Call._capnp.defaultNoPromisePipelining); }
    setNoPromisePipelining(value: boolean): void { __S.setBit(129, value, this, Call._capnp.defaultNoPromisePipelining); }
    get noPromisePipelining(): boolean { return this.getNoPromisePipelining(); }
    set noPromisePipelining(value: boolean) { this.setNoPromisePipelining(value); }
    getOnlyPromisePipeline(): boolean { return __S.getBit(130, this, Call._capnp.defaultOnlyPromisePipeline); }
    setOnlyPromisePipeline(value: boolean): void { __S.setBit(130, value, this, Call._capnp.defaultOnlyPromisePipeline); }
    get onlyPromisePipeline(): boolean { return this.getOnlyPromisePipeline(); }
    set onlyPromisePipeline(value: boolean) { this.setOnlyPromisePipeline(value); }
    adoptParams(value: capnp.Orphan<Payload>): void { __S.adopt(value, __S.getPointer(1, this)); }
    disownParams(): capnp.Orphan<Payload> { return __S.disown(this.getParams()); }
    getParams(): Payload { return __S.getStruct(1, Payload, this); }
    hasParams(): boolean { return !__S.isNull(__S.getPointer(1, this)); }
    initParams(): Payload { return __S.initStructAt(1, Payload, this); }
    setParams(value: Payload): void { __S.copyFrom(value, __S.getPointer(1, this)); }
    get params(): Payload { return this.getParams(); }
    set params(value: Payload | Payload_Shape) { if (value instanceof Payload) { this.setParams(value); } else { this.initParams().set(value); } }
    getSendResultsTo(): Call_SendResultsTo { return __S.getAs(Call_SendResultsTo, this); }
    initSendResultsTo(): Call_SendResultsTo { return __S.getAs(Call_SendResultsTo, this); }
    get sendResultsTo(): Call_SendResultsTo { return this.getSendResultsTo(); }
    set sendResultsTo(value: Call_SendResultsTo_Shape) { this.initSendResultsTo().set(value); }
    set(value: Call_Shape): void {
        if (value.questionId !== undefined) this.setQuestionId(value.questionId);
        if (value.target !== undefined) this.initTarget().set(value.target);
        if (value.interfaceId !== undefined) this.setInterfaceId(BigInt(value.interfaceId));
        if (value.methodId !== undefined) this.setMethodId(value.methodId);
        if (value.allowThirdPartyTailCall !== undefined) this.setAllowThirdPartyTailCall(value.allowThirdPartyTailCall);
        if (value.noPromisePipelining !== undefined) this.setNoPromisePipelining(value.noPromisePipelining);
        if (value.onlyPromisePipeline !== undefined) this.setOnlyPromisePipeline(value.onlyPromisePipeline);
        if (value.params !== undefined) this.initParams().set(value.params);
        if (value.sendResultsTo !== undefined) this.initSendResultsTo().set(value.sendResultsTo);
    }
    get(): Call_Json {
        return {
            questionId: this.getQuestionId(),
            ...(this.hasTarget() ? { target: this.getTarget().get() } : {}),
            interfaceId: this.getInterfaceId().toString(),
            methodId: this.getMethodId(),
            allowThirdPartyTailCall: this.getAllowThirdPartyTailCall(),
            noPromisePipelining: this.getNoPromisePipelining(),
            onlyPromisePipeline: this.getOnlyPromisePipeline(),
            ...(this.hasParams() ? { params: this.getParams().get() } : {}),
            sendResultsTo: this.getSendResultsTo().get(),
        };
    }
    toJSON(): Call_Json { return this.get(); }
    toString(): string { return "Call_" + super.toString(); }
}
export namespace Call {
    export type Json = Call_Json;
    export import SendResultsTo = Call_SendResultsTo;
    export type Shape = Call_Shape;
}
export enum Return_Which {
    RESULTS = 0,
    EXCEPTION = 1,
    CANCELED = 2,
    RESULTS_SENT_ELSEWHERE = 3,
    TAKE_FROM_OTHER_QUESTION = 4,
    ACCEPT_FROM_THIRD_PARTY = 5
}
export interface Return_Shape {
    answerId?: number;
    releaseParamCaps?: boolean;
    noFinishNeeded?: boolean;
    results?: Payload_Shape;
    exception?: Exception_Shape;
    canceled?: null;
    resultsSentElsewhere?: null;
    takeFromOtherQuestion?: number;
}
export interface Return_Json {
    answerId: number;
    releaseParamCaps: boolean;
    noFinishNeeded: boolean;
    results?: Payload_Json;
    exception?: Exception_Json;
    canceled?: null;
    resultsSentElsewhere?: null;
    takeFromOtherQuestion?: number;
}
export class Return extends __S {
    static readonly RESULTS = Return_Which.RESULTS;
    static readonly EXCEPTION = Return_Which.EXCEPTION;
    static readonly CANCELED = Return_Which.CANCELED;
    static readonly RESULTS_SENT_ELSEWHERE = Return_Which.RESULTS_SENT_ELSEWHERE;
    static readonly TAKE_FROM_OTHER_QUESTION = Return_Which.TAKE_FROM_OTHER_QUESTION;
    static readonly ACCEPT_FROM_THIRD_PARTY = Return_Which.ACCEPT_FROM_THIRD_PARTY;
    static readonly _capnp = { displayName: "Return", id: "9e19b28d3db3573a", size: new __O(16, 1), defaultReleaseParamCaps: capnp.getBitMask(true, 0), defaultNoFinishNeeded: capnp.getBitMask(false, 1) };
    getAnswerId(): number { return __S.getUint32(0, this); }
    setAnswerId(value: number): void { __S.setUint32(0, value, this); }
    get answerId(): number { return this.getAnswerId(); }
    set answerId(value: number) { this.setAnswerId(value); }
    getReleaseParamCaps(): boolean { return __S.getBit(32, this, Return._capnp.defaultReleaseParamCaps); }
    setReleaseParamCaps(value: boolean): void { __S.setBit(32, value, this, Return._capnp.defaultReleaseParamCaps); }
    get releaseParamCaps(): boolean { return this.getReleaseParamCaps(); }
    set releaseParamCaps(value: boolean) { this.setReleaseParamCaps(value); }
    getNoFinishNeeded(): boolean { return __S.getBit(33, this, Return._capnp.defaultNoFinishNeeded); }
    setNoFinishNeeded(value: boolean): void { __S.setBit(33, value, this, Return._capnp.defaultNoFinishNeeded); }
    get noFinishNeeded(): boolean { return this.getNoFinishNeeded(); }
    set noFinishNeeded(value: boolean) { this.setNoFinishNeeded(value); }
    adoptResults(value: capnp.Orphan<Payload>): void {
        __S.setUint16(6, 0, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownResults(): capnp.Orphan<Payload> { return __S.disown(this.getResults()); }
    getResults(): Payload {
        __S.testWhich("results", __S.getUint16(6, this), 0, this);
        return __S.getStruct(0, Payload, this);
    }
    hasResults(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initResults(): Payload {
        __S.setUint16(6, 0, this);
        return __S.initStructAt(0, Payload, this);
    }
    isResults(): boolean { return __S.getUint16(6, this) === 0; }
    setResults(value: Payload): void {
        __S.setUint16(6, 0, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get results(): Payload { return this.getResults(); }
    set results(value: Payload | Payload_Shape) { if (value instanceof Payload) { this.setResults(value); } else { this.initResults().set(value); } }
    adoptException(value: capnp.Orphan<Exception>): void {
        __S.setUint16(6, 1, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownException(): capnp.Orphan<Exception> { return __S.disown(this.getException()); }
    getException(): Exception {
        __S.testWhich("exception", __S.getUint16(6, this), 1, this);
        return __S.getStruct(0, Exception, this);
    }
    hasException(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initException(): Exception {
        __S.setUint16(6, 1, this);
        return __S.initStructAt(0, Exception, this);
    }
    isException(): boolean { return __S.getUint16(6, this) === 1; }
    setException(value: Exception): void {
        __S.setUint16(6, 1, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get exception(): Exception { return this.getException(); }
    set exception(value: Exception | Exception_Shape) { if (value instanceof Exception) { this.setException(value); } else { this.initException().set(value); } }
    isCanceled(): boolean { return __S.getUint16(6, this) === 2; }
    setCanceled(): void { __S.setUint16(6, 2, this); }
    isResultsSentElsewhere(): boolean { return __S.getUint16(6, this) === 3; }
    setResultsSentElsewhere(): void { __S.setUint16(6, 3, this); }
    getTakeFromOtherQuestion(): number {
        __S.testWhich("takeFromOtherQuestion", __S.getUint16(6, this), 4, this);
        return __S.getUint32(8, this);
    }
    isTakeFromOtherQuestion(): boolean { return __S.getUint16(6, this) === 4; }
    setTakeFromOtherQuestion(value: number): void {
        __S.setUint16(6, 4, this);
        __S.setUint32(8, value, this);
    }
    get takeFromOtherQuestion(): number { return this.getTakeFromOtherQuestion(); }
    set takeFromOtherQuestion(value: number) { this.setTakeFromOtherQuestion(value); }
    adoptAcceptFromThirdParty(value: capnp.Orphan<capnp.Pointer>): void {
        __S.setUint16(6, 5, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownAcceptFromThirdParty(): capnp.Orphan<capnp.Pointer> { return __S.disown(this.getAcceptFromThirdParty()); }
    getAcceptFromThirdParty(): capnp.Pointer {
        __S.testWhich("acceptFromThirdParty", __S.getUint16(6, this), 5, this);
        return __S.getPointer(0, this);
    }
    hasAcceptFromThirdParty(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    isAcceptFromThirdParty(): boolean { return __S.getUint16(6, this) === 5; }
    setAcceptFromThirdParty(value: capnp.Pointer): void {
        __S.setUint16(6, 5, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get acceptFromThirdParty(): capnp.Pointer { return this.getAcceptFromThirdParty(); }
    set acceptFromThirdParty(value: capnp.Pointer) { this.setAcceptFromThirdParty(value); }
    set(value: Return_Shape): void {
        if (value.answerId !== undefined) this.setAnswerId(value.answerId);
        if (value.releaseParamCaps !== undefined) this.setReleaseParamCaps(value.releaseParamCaps);
        if (value.noFinishNeeded !== undefined) this.setNoFinishNeeded(value.noFinishNeeded);
        if (value.results !== undefined) this.initResults().set(value.results);
        if (value.exception !== undefined) this.initException().set(value.exception);
        if (value.canceled !== undefined) this.setCanceled();
        if (value.resultsSentElsewhere !== undefined) this.setResultsSentElsewhere();
        if (value.takeFromOtherQuestion !== undefined) this.setTakeFromOtherQuestion(value.takeFromOtherQuestion);
    }
    get(): Return_Json {
        return {
            answerId: this.getAnswerId(),
            releaseParamCaps: this.getReleaseParamCaps(),
            noFinishNeeded: this.getNoFinishNeeded(),
            ...(this.isResults() && this.hasResults() ? { results: this.getResults().get() } : {}),
            ...(this.isException() && this.hasException() ? { exception: this.getException().get() } : {}),
            ...(this.isCanceled() ? { canceled: null } : {}),
            ...(this.isResultsSentElsewhere() ? { resultsSentElsewhere: null } : {}),
            ...(this.isTakeFromOtherQuestion() ? { takeFromOtherQuestion: this.getTakeFromOtherQuestion() } : {}),
        };
    }
    toJSON(): Return_Json { return this.get(); }
    toString(): string { return "Return_" + super.toString(); }
    which(): Return_Which { return __S.getUint16(6, this); }
}
export namespace Return {
    export type Json = Return_Json;
    export type Shape = Return_Shape;
    export import Which = Return_Which;
}
export interface Finish_Shape {
    questionId?: number;
    releaseResultCaps?: boolean;
    requireEarlyCancellationWorkaround?: boolean;
}
export interface Finish_Json {
    questionId: number;
    releaseResultCaps: boolean;
    requireEarlyCancellationWorkaround: boolean;
}
export class Finish extends __S {
    static readonly _capnp = { displayName: "Finish", id: "d37d2eb2c2f80e63", size: new __O(8, 0), defaultReleaseResultCaps: capnp.getBitMask(true, 0), defaultRequireEarlyCancellationWorkaround: capnp.getBitMask(true, 1) };
    getQuestionId(): number { return __S.getUint32(0, this); }
    setQuestionId(value: number): void { __S.setUint32(0, value, this); }
    get questionId(): number { return this.getQuestionId(); }
    set questionId(value: number) { this.setQuestionId(value); }
    getReleaseResultCaps(): boolean { return __S.getBit(32, this, Finish._capnp.defaultReleaseResultCaps); }
    setReleaseResultCaps(value: boolean): void { __S.setBit(32, value, this, Finish._capnp.defaultReleaseResultCaps); }
    get releaseResultCaps(): boolean { return this.getReleaseResultCaps(); }
    set releaseResultCaps(value: boolean) { this.setReleaseResultCaps(value); }
    getRequireEarlyCancellationWorkaround(): boolean { return __S.getBit(33, this, Finish._capnp.defaultRequireEarlyCancellationWorkaround); }
    setRequireEarlyCancellationWorkaround(value: boolean): void { __S.setBit(33, value, this, Finish._capnp.defaultRequireEarlyCancellationWorkaround); }
    get requireEarlyCancellationWorkaround(): boolean { return this.getRequireEarlyCancellationWorkaround(); }
    set requireEarlyCancellationWorkaround(value: boolean) { this.setRequireEarlyCancellationWorkaround(value); }
    set(value: Finish_Shape): void {
        if (value.questionId !== undefined) this.setQuestionId(value.questionId);
        if (value.releaseResultCaps !== undefined) this.setReleaseResultCaps(value.releaseResultCaps);
        if (value.requireEarlyCancellationWorkaround !== undefined) this.setRequireEarlyCancellationWorkaround(value.requireEarlyCancellationWorkaround);
    }
    get(): Finish_Json {
        return {
            questionId: this.getQuestionId(),
            releaseResultCaps: this.getReleaseResultCaps(),
            requireEarlyCancellationWorkaround: this.getRequireEarlyCancellationWorkaround(),
        };
    }
    toJSON(): Finish_Json { return this.get(); }
    toString(): string { return "Finish_" + super.toString(); }
}
export namespace Finish {
    export type Json = Finish_Json;
    export type Shape = Finish_Shape;
}
export enum Resolve_Which {
    CAP = 0,
    EXCEPTION = 1
}
export interface Resolve_Shape {
    promiseId?: number;
    cap?: CapDescriptor_Shape;
    exception?: Exception_Shape;
}
export interface Resolve_Json {
    promiseId: number;
    cap?: CapDescriptor_Json;
    exception?: Exception_Json;
}
export class Resolve extends __S {
    static readonly CAP = Resolve_Which.CAP;
    static readonly EXCEPTION = Resolve_Which.EXCEPTION;
    static readonly _capnp = { displayName: "Resolve", id: "bbc29655fa89086e", size: new __O(8, 1) };
    getPromiseId(): number { return __S.getUint32(0, this); }
    setPromiseId(value: number): void { __S.setUint32(0, value, this); }
    get promiseId(): number { return this.getPromiseId(); }
    set promiseId(value: number) { this.setPromiseId(value); }
    adoptCap(value: capnp.Orphan<CapDescriptor>): void {
        __S.setUint16(4, 0, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownCap(): capnp.Orphan<CapDescriptor> { return __S.disown(this.getCap()); }
    getCap(): CapDescriptor {
        __S.testWhich("cap", __S.getUint16(4, this), 0, this);
        return __S.getStruct(0, CapDescriptor, this);
    }
    hasCap(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initCap(): CapDescriptor {
        __S.setUint16(4, 0, this);
        return __S.initStructAt(0, CapDescriptor, this);
    }
    isCap(): boolean { return __S.getUint16(4, this) === 0; }
    setCap(value: CapDescriptor): void {
        __S.setUint16(4, 0, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get cap(): CapDescriptor { return this.getCap(); }
    set cap(value: CapDescriptor | CapDescriptor_Shape) { if (value instanceof CapDescriptor) { this.setCap(value); } else { this.initCap().set(value); } }
    adoptException(value: capnp.Orphan<Exception>): void {
        __S.setUint16(4, 1, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownException(): capnp.Orphan<Exception> { return __S.disown(this.getException()); }
    getException(): Exception {
        __S.testWhich("exception", __S.getUint16(4, this), 1, this);
        return __S.getStruct(0, Exception, this);
    }
    hasException(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initException(): Exception {
        __S.setUint16(4, 1, this);
        return __S.initStructAt(0, Exception, this);
    }
    isException(): boolean { return __S.getUint16(4, this) === 1; }
    setException(value: Exception): void {
        __S.setUint16(4, 1, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get exception(): Exception { return this.getException(); }
    set exception(value: Exception | Exception_Shape) { if (value instanceof Exception) { this.setException(value); } else { this.initException().set(value); } }
    set(value: Resolve_Shape): void {
        if (value.promiseId !== undefined) this.setPromiseId(value.promiseId);
        if (value.cap !== undefined) this.initCap().set(value.cap);
        if (value.exception !== undefined) this.initException().set(value.exception);
    }
    get(): Resolve_Json {
        return {
            promiseId: this.getPromiseId(),
            ...(this.isCap() && this.hasCap() ? { cap: this.getCap().get() } : {}),
            ...(this.isException() && this.hasException() ? { exception: this.getException().get() } : {}),
        };
    }
    toJSON(): Resolve_Json { return this.get(); }
    toString(): string { return "Resolve_" + super.toString(); }
    which(): Resolve_Which { return __S.getUint16(4, this); }
}
export namespace Resolve {
    export type Json = Resolve_Json;
    export type Shape = Resolve_Shape;
    export import Which = Resolve_Which;
}
export interface Release_Shape {
    id?: number;
    referenceCount?: number;
}
export interface Release_Json {
    id: number;
    referenceCount: number;
}
export class Release extends __S {
    static readonly _capnp = { displayName: "Release", id: "ad1a6c0d7dd07497", size: new __O(8, 0) };
    getId(): number { return __S.getUint32(0, this); }
    setId(value: number): void { __S.setUint32(0, value, this); }
    get id(): number { return this.getId(); }
    set id(value: number) { this.setId(value); }
    getReferenceCount(): number { return __S.getUint32(4, this); }
    setReferenceCount(value: number): void { __S.setUint32(4, value, this); }
    get referenceCount(): number { return this.getReferenceCount(); }
    set referenceCount(value: number) { this.setReferenceCount(value); }
    set(value: Release_Shape): void {
        if (value.id !== undefined) this.setId(value.id);
        if (value.referenceCount !== undefined) this.setReferenceCount(value.referenceCount);
    }
    get(): Release_Json {
        return {
            id: this.getId(),
            referenceCount: this.getReferenceCount(),
        };
    }
    toJSON(): Release_Json { return this.get(); }
    toString(): string { return "Release_" + super.toString(); }
}
export namespace Release {
    export type Json = Release_Json;
    export type Shape = Release_Shape;
}
export enum Disembargo_Context_Which {
    SENDER_LOOPBACK = 0,
    RECEIVER_LOOPBACK = 1,
    ACCEPT = 2,
    PROVIDE = 3
}
export interface Disembargo_Context_Shape {
    senderLoopback?: number;
    receiverLoopback?: number;
    accept?: null;
    provide?: number;
}
export interface Disembargo_Context_Json {
    senderLoopback?: number;
    receiverLoopback?: number;
    accept?: null;
    provide?: number;
}
export class Disembargo_Context extends __S {
    static readonly SENDER_LOOPBACK = Disembargo_Context_Which.SENDER_LOOPBACK;
    static readonly RECEIVER_LOOPBACK = Disembargo_Context_Which.RECEIVER_LOOPBACK;
    static readonly ACCEPT = Disembargo_Context_Which.ACCEPT;
    static readonly PROVIDE = Disembargo_Context_Which.PROVIDE;
    static readonly _capnp = { displayName: "context", id: "d562b4df655bdd4d", size: new __O(8, 1) };
    getSenderLoopback(): number {
        __S.testWhich("senderLoopback", __S.getUint16(4, this), 0, this);
        return __S.getUint32(0, this);
    }
    isSenderLoopback(): boolean { return __S.getUint16(4, this) === 0; }
    setSenderLoopback(value: number): void {
        __S.setUint16(4, 0, this);
        __S.setUint32(0, value, this);
    }
    get senderLoopback(): number { return this.getSenderLoopback(); }
    set senderLoopback(value: number) { this.setSenderLoopback(value); }
    getReceiverLoopback(): number {
        __S.testWhich("receiverLoopback", __S.getUint16(4, this), 1, this);
        return __S.getUint32(0, this);
    }
    isReceiverLoopback(): boolean { return __S.getUint16(4, this) === 1; }
    setReceiverLoopback(value: number): void {
        __S.setUint16(4, 1, this);
        __S.setUint32(0, value, this);
    }
    get receiverLoopback(): number { return this.getReceiverLoopback(); }
    set receiverLoopback(value: number) { this.setReceiverLoopback(value); }
    isAccept(): boolean { return __S.getUint16(4, this) === 2; }
    setAccept(): void { __S.setUint16(4, 2, this); }
    getProvide(): number {
        __S.testWhich("provide", __S.getUint16(4, this), 3, this);
        return __S.getUint32(0, this);
    }
    isProvide(): boolean { return __S.getUint16(4, this) === 3; }
    setProvide(value: number): void {
        __S.setUint16(4, 3, this);
        __S.setUint32(0, value, this);
    }
    get provide(): number { return this.getProvide(); }
    set provide(value: number) { this.setProvide(value); }
    set(value: Disembargo_Context_Shape): void {
        if (value.senderLoopback !== undefined) this.setSenderLoopback(value.senderLoopback);
        if (value.receiverLoopback !== undefined) this.setReceiverLoopback(value.receiverLoopback);
        if (value.accept !== undefined) this.setAccept();
        if (value.provide !== undefined) this.setProvide(value.provide);
    }
    get(): Disembargo_Context_Json {
        return {
            ...(this.isSenderLoopback() ? { senderLoopback: this.getSenderLoopback() } : {}),
            ...(this.isReceiverLoopback() ? { receiverLoopback: this.getReceiverLoopback() } : {}),
            ...(this.isAccept() ? { accept: null } : {}),
            ...(this.isProvide() ? { provide: this.getProvide() } : {}),
        };
    }
    toJSON(): Disembargo_Context_Json { return this.get(); }
    toString(): string { return "Disembargo_Context_" + super.toString(); }
    which(): Disembargo_Context_Which { return __S.getUint16(4, this); }
}
export namespace Disembargo_Context {
    export type Json = Disembargo_Context_Json;
    export type Shape = Disembargo_Context_Shape;
    export import Which = Disembargo_Context_Which;
}
export interface Disembargo_Shape {
    target?: MessageTarget_Shape;
    context?: Disembargo_Context_Shape;
}
export interface Disembargo_Json {
    target?: MessageTarget_Json;
    context: Disembargo_Context_Json;
}
export class Disembargo extends __S {
    static readonly _capnp = { displayName: "Disembargo", id: "f964368b0fbd3711", size: new __O(8, 1) };
    adoptTarget(value: capnp.Orphan<MessageTarget>): void { __S.adopt(value, __S.getPointer(0, this)); }
    disownTarget(): capnp.Orphan<MessageTarget> { return __S.disown(this.getTarget()); }
    getTarget(): MessageTarget { return __S.getStruct(0, MessageTarget, this); }
    hasTarget(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initTarget(): MessageTarget { return __S.initStructAt(0, MessageTarget, this); }
    setTarget(value: MessageTarget): void { __S.copyFrom(value, __S.getPointer(0, this)); }
    get target(): MessageTarget { return this.getTarget(); }
    set target(value: MessageTarget | MessageTarget_Shape) { if (value instanceof MessageTarget) { this.setTarget(value); } else { this.initTarget().set(value); } }
    getContext(): Disembargo_Context { return __S.getAs(Disembargo_Context, this); }
    initContext(): Disembargo_Context { return __S.getAs(Disembargo_Context, this); }
    get context(): Disembargo_Context { return this.getContext(); }
    set context(value: Disembargo_Context_Shape) { this.initContext().set(value); }
    set(value: Disembargo_Shape): void {
        if (value.target !== undefined) this.initTarget().set(value.target);
        if (value.context !== undefined) this.initContext().set(value.context);
    }
    get(): Disembargo_Json {
        return {
            ...(this.hasTarget() ? { target: this.getTarget().get() } : {}),
            context: this.getContext().get(),
        };
    }
    toJSON(): Disembargo_Json { return this.get(); }
    toString(): string { return "Disembargo_" + super.toString(); }
}
export namespace Disembargo {
    export import Context = Disembargo_Context;
    export type Json = Disembargo_Json;
    export type Shape = Disembargo_Shape;
}
export interface Provide_Shape {
    questionId?: number;
    target?: MessageTarget_Shape;
}
export interface Provide_Json {
    questionId: number;
    target?: MessageTarget_Json;
}
export class Provide extends __S {
    static readonly _capnp = { displayName: "Provide", id: "9c6a046bfbc1ac5a", size: new __O(8, 2) };
    getQuestionId(): number { return __S.getUint32(0, this); }
    setQuestionId(value: number): void { __S.setUint32(0, value, this); }
    get questionId(): number { return this.getQuestionId(); }
    set questionId(value: number) { this.setQuestionId(value); }
    adoptTarget(value: capnp.Orphan<MessageTarget>): void { __S.adopt(value, __S.getPointer(0, this)); }
    disownTarget(): capnp.Orphan<MessageTarget> { return __S.disown(this.getTarget()); }
    getTarget(): MessageTarget { return __S.getStruct(0, MessageTarget, this); }
    hasTarget(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initTarget(): MessageTarget { return __S.initStructAt(0, MessageTarget, this); }
    setTarget(value: MessageTarget): void { __S.copyFrom(value, __S.getPointer(0, this)); }
    get target(): MessageTarget { return this.getTarget(); }
    set target(value: MessageTarget | MessageTarget_Shape) { if (value instanceof MessageTarget) { this.setTarget(value); } else { this.initTarget().set(value); } }
    adoptRecipient(value: capnp.Orphan<capnp.Pointer>): void { __S.adopt(value, __S.getPointer(1, this)); }
    disownRecipient(): capnp.Orphan<capnp.Pointer> { return __S.disown(this.getRecipient()); }
    getRecipient(): capnp.Pointer { return __S.getPointer(1, this); }
    hasRecipient(): boolean { return !__S.isNull(__S.getPointer(1, this)); }
    setRecipient(value: capnp.Pointer): void { __S.copyFrom(value, __S.getPointer(1, this)); }
    get recipient(): capnp.Pointer { return this.getRecipient(); }
    set recipient(value: capnp.Pointer) { this.setRecipient(value); }
    set(value: Provide_Shape): void {
        if (value.questionId !== undefined) this.setQuestionId(value.questionId);
        if (value.target !== undefined) this.initTarget().set(value.target);
    }
    get(): Provide_Json {
        return {
            questionId: this.getQuestionId(),
            ...(this.hasTarget() ? { target: this.getTarget().get() } : {}),
        };
    }
    toJSON(): Provide_Json { return this.get(); }
    toString(): string { return "Provide_" + super.toString(); }
}
export namespace Provide {
    export type Json = Provide_Json;
    export type Shape = Provide_Shape;
}
export interface Accept_Shape {
    questionId?: number;
    embargo?: boolean;
}
export interface Accept_Json {
    questionId: number;
    embargo: boolean;
}
export class Accept extends __S {
    static readonly _capnp = { displayName: "Accept", id: "d4c9b56290554016", size: new __O(8, 1) };
    getQuestionId(): number { return __S.getUint32(0, this); }
    setQuestionId(value: number): void { __S.setUint32(0, value, this); }
    get questionId(): number { return this.getQuestionId(); }
    set questionId(value: number) { this.setQuestionId(value); }
    adoptProvision(value: capnp.Orphan<capnp.Pointer>): void { __S.adopt(value, __S.getPointer(0, this)); }
    disownProvision(): capnp.Orphan<capnp.Pointer> { return __S.disown(this.getProvision()); }
    getProvision(): capnp.Pointer { return __S.getPointer(0, this); }
    hasProvision(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    setProvision(value: capnp.Pointer): void { __S.copyFrom(value, __S.getPointer(0, this)); }
    get provision(): capnp.Pointer { return this.getProvision(); }
    set provision(value: capnp.Pointer) { this.setProvision(value); }
    getEmbargo(): boolean { return __S.getBit(32, this); }
    setEmbargo(value: boolean): void { __S.setBit(32, value, this); }
    get embargo(): boolean { return this.getEmbargo(); }
    set embargo(value: boolean) { this.setEmbargo(value); }
    set(value: Accept_Shape): void {
        if (value.questionId !== undefined) this.setQuestionId(value.questionId);
        if (value.embargo !== undefined) this.setEmbargo(value.embargo);
    }
    get(): Accept_Json {
        return {
            questionId: this.getQuestionId(),
            embargo: this.getEmbargo(),
        };
    }
    toJSON(): Accept_Json { return this.get(); }
    toString(): string { return "Accept_" + super.toString(); }
}
export namespace Accept {
    export type Json = Accept_Json;
    export type Shape = Accept_Shape;
}
export interface Join_Shape {
    questionId?: number;
    target?: MessageTarget_Shape;
}
export interface Join_Json {
    questionId: number;
    target?: MessageTarget_Json;
}
export class Join extends __S {
    static readonly _capnp = { displayName: "Join", id: "fbe1980490e001af", size: new __O(8, 2) };
    getQuestionId(): number { return __S.getUint32(0, this); }
    setQuestionId(value: number): void { __S.setUint32(0, value, this); }
    get questionId(): number { return this.getQuestionId(); }
    set questionId(value: number) { this.setQuestionId(value); }
    adoptTarget(value: capnp.Orphan<MessageTarget>): void { __S.adopt(value, __S.getPointer(0, this)); }
    disownTarget(): capnp.Orphan<MessageTarget> { return __S.disown(this.getTarget()); }
    getTarget(): MessageTarget { return __S.getStruct(0, MessageTarget, this); }
    hasTarget(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initTarget(): MessageTarget { return __S.initStructAt(0, MessageTarget, this); }
    setTarget(value: MessageTarget): void { __S.copyFrom(value, __S.getPointer(0, this)); }
    get target(): MessageTarget { return this.getTarget(); }
    set target(value: MessageTarget | MessageTarget_Shape) { if (value instanceof MessageTarget) { this.setTarget(value); } else { this.initTarget().set(value); } }
    adoptKeyPart(value: capnp.Orphan<capnp.Pointer>): void { __S.adopt(value, __S.getPointer(1, this)); }
    disownKeyPart(): capnp.Orphan<capnp.Pointer> { return __S.disown(this.getKeyPart()); }
    getKeyPart(): capnp.Pointer { return __S.getPointer(1, this); }
    hasKeyPart(): boolean { return !__S.isNull(__S.getPointer(1, this)); }
    setKeyPart(value: capnp.Pointer): void { __S.copyFrom(value, __S.getPointer(1, this)); }
    get keyPart(): capnp.Pointer { return this.getKeyPart(); }
    set keyPart(value: capnp.Pointer) { this.setKeyPart(value); }
    set(value: Join_Shape): void {
        if (value.questionId !== undefined) this.setQuestionId(value.questionId);
        if (value.target !== undefined) this.initTarget().set(value.target);
    }
    get(): Join_Json {
        return {
            questionId: this.getQuestionId(),
            ...(this.hasTarget() ? { target: this.getTarget().get() } : {}),
        };
    }
    toJSON(): Join_Json { return this.get(); }
    toString(): string { return "Join_" + super.toString(); }
}
export namespace Join {
    export type Json = Join_Json;
    export type Shape = Join_Shape;
}
export enum MessageTarget_Which {
    IMPORTED_CAP = 0,
    PROMISED_ANSWER = 1
}
export interface MessageTarget_Shape {
    importedCap?: number;
    promisedAnswer?: PromisedAnswer_Shape;
}
export interface MessageTarget_Json {
    importedCap?: number;
    promisedAnswer?: PromisedAnswer_Json;
}
export class MessageTarget extends __S {
    static readonly IMPORTED_CAP = MessageTarget_Which.IMPORTED_CAP;
    static readonly PROMISED_ANSWER = MessageTarget_Which.PROMISED_ANSWER;
    static readonly _capnp = { displayName: "MessageTarget", id: "95bc14545813fbc1", size: new __O(8, 1) };
    getImportedCap(): number {
        __S.testWhich("importedCap", __S.getUint16(4, this), 0, this);
        return __S.getUint32(0, this);
    }
    isImportedCap(): boolean { return __S.getUint16(4, this) === 0; }
    setImportedCap(value: number): void {
        __S.setUint16(4, 0, this);
        __S.setUint32(0, value, this);
    }
    get importedCap(): number { return this.getImportedCap(); }
    set importedCap(value: number) { this.setImportedCap(value); }
    adoptPromisedAnswer(value: capnp.Orphan<PromisedAnswer>): void {
        __S.setUint16(4, 1, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownPromisedAnswer(): capnp.Orphan<PromisedAnswer> { return __S.disown(this.getPromisedAnswer()); }
    getPromisedAnswer(): PromisedAnswer {
        __S.testWhich("promisedAnswer", __S.getUint16(4, this), 1, this);
        return __S.getStruct(0, PromisedAnswer, this);
    }
    hasPromisedAnswer(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initPromisedAnswer(): PromisedAnswer {
        __S.setUint16(4, 1, this);
        return __S.initStructAt(0, PromisedAnswer, this);
    }
    isPromisedAnswer(): boolean { return __S.getUint16(4, this) === 1; }
    setPromisedAnswer(value: PromisedAnswer): void {
        __S.setUint16(4, 1, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get promisedAnswer(): PromisedAnswer { return this.getPromisedAnswer(); }
    set promisedAnswer(value: PromisedAnswer | PromisedAnswer_Shape) { if (value instanceof PromisedAnswer) { this.setPromisedAnswer(value); } else { this.initPromisedAnswer().set(value); } }
    set(value: MessageTarget_Shape): void {
        if (value.importedCap !== undefined) this.setImportedCap(value.importedCap);
        if (value.promisedAnswer !== undefined) this.initPromisedAnswer().set(value.promisedAnswer);
    }
    get(): MessageTarget_Json {
        return {
            ...(this.isImportedCap() ? { importedCap: this.getImportedCap() } : {}),
            ...(this.isPromisedAnswer() && this.hasPromisedAnswer() ? { promisedAnswer: this.getPromisedAnswer().get() } : {}),
        };
    }
    toJSON(): MessageTarget_Json { return this.get(); }
    toString(): string { return "MessageTarget_" + super.toString(); }
    which(): MessageTarget_Which { return __S.getUint16(4, this); }
}
export namespace MessageTarget {
    export type Json = MessageTarget_Json;
    export type Shape = MessageTarget_Shape;
    export import Which = MessageTarget_Which;
}
export interface Payload_Shape {
    capTable?: readonly CapDescriptor_Shape[];
}
export interface Payload_Json {
    capTable?: CapDescriptor_Json[];
}
export class Payload extends __S {
    static readonly _capnp = { displayName: "Payload", id: "9a0e61223d96743b", size: new __O(0, 2) };
    static _CapTable: capnp.ListCtor<CapDescriptor>;
    adoptContent(value: capnp.Orphan<capnp.Pointer>): void { __S.adopt(value, __S.getPointer(0, this)); }
    disownContent(): capnp.Orphan<capnp.Pointer> { return __S.disown(this.getContent()); }
    getContent(): capnp.Pointer { return __S.getPointer(0, this); }
    hasContent(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    setContent(value: capnp.Pointer): void { __S.copyFrom(value, __S.getPointer(0, this)); }
    get content(): capnp.Pointer { return this.getContent(); }
    set content(value: capnp.Pointer) { this.setContent(value); }
    adoptCapTable(value: capnp.Orphan<capnp.List<CapDescriptor>>): void { __S.adopt(value, __S.getPointer(1, this)); }
    disownCapTable(): capnp.Orphan<capnp.List<CapDescriptor>> { return __S.disown(this.getCapTable()); }
    getCapTable(): capnp.List<CapDescriptor> { return __S.getList(1, Payload._CapTable, this); }
    hasCapTable(): boolean { return !__S.isNull(__S.getPointer(1, this)); }
    initCapTable(length: number): capnp.List<CapDescriptor> { return __S.initList(1, Payload._CapTable, length, this); }
    setCapTable(value: capnp.List<CapDescriptor>): void { __S.copyFrom(value, __S.getPointer(1, this)); }
    get capTable(): capnp.List<CapDescriptor> { return this.getCapTable(); }
    set capTable(value: capnp.List<CapDescriptor> | readonly CapDescriptor_Shape[]) { if (value instanceof capnp.List) { this.setCapTable(value); } else { this.set({ capTable: value }); } }
    set(value: Payload_Shape): void {
        if (value.capTable !== undefined) {
            const l = this.initCapTable(value.capTable.length);
            value.capTable.forEach((e, i) => l.get(i).set(e));
        }
    }
    get(): Payload_Json {
        return {
            ...(this.hasCapTable() ? { capTable: this.getCapTable().toArray().map((e) => e.get()) } : {}),
        };
    }
    toJSON(): Payload_Json { return this.get(); }
    toString(): string { return "Payload_" + super.toString(); }
}
export namespace Payload {
    export type Json = Payload_Json;
    export type Shape = Payload_Shape;
}
export enum CapDescriptor_Which {
    NONE = 0,
    SENDER_HOSTED = 1,
    SENDER_PROMISE = 2,
    RECEIVER_HOSTED = 3,
    RECEIVER_ANSWER = 4,
    THIRD_PARTY_HOSTED = 5
}
export interface CapDescriptor_Shape {
    none?: null;
    senderHosted?: number;
    senderPromise?: number;
    receiverHosted?: number;
    receiverAnswer?: PromisedAnswer_Shape;
    thirdPartyHosted?: ThirdPartyCapDescriptor_Shape;
    attachedFd?: number;
}
export interface CapDescriptor_Json {
    none?: null;
    senderHosted?: number;
    senderPromise?: number;
    receiverHosted?: number;
    receiverAnswer?: PromisedAnswer_Json;
    thirdPartyHosted?: ThirdPartyCapDescriptor_Json;
    attachedFd: number;
}
export class CapDescriptor extends __S {
    static readonly NONE = CapDescriptor_Which.NONE;
    static readonly SENDER_HOSTED = CapDescriptor_Which.SENDER_HOSTED;
    static readonly SENDER_PROMISE = CapDescriptor_Which.SENDER_PROMISE;
    static readonly RECEIVER_HOSTED = CapDescriptor_Which.RECEIVER_HOSTED;
    static readonly RECEIVER_ANSWER = CapDescriptor_Which.RECEIVER_ANSWER;
    static readonly THIRD_PARTY_HOSTED = CapDescriptor_Which.THIRD_PARTY_HOSTED;
    static readonly _capnp = { displayName: "CapDescriptor", id: "8523ddc40b86b8b0", size: new __O(8, 1), defaultAttachedFd: capnp.getUint8Mask(255) };
    isNone(): boolean { return __S.getUint16(0, this) === 0; }
    setNone(): void { __S.setUint16(0, 0, this); }
    getSenderHosted(): number {
        __S.testWhich("senderHosted", __S.getUint16(0, this), 1, this);
        return __S.getUint32(4, this);
    }
    isSenderHosted(): boolean { return __S.getUint16(0, this) === 1; }
    setSenderHosted(value: number): void {
        __S.setUint16(0, 1, this);
        __S.setUint32(4, value, this);
    }
    get senderHosted(): number { return this.getSenderHosted(); }
    set senderHosted(value: number) { this.setSenderHosted(value); }
    getSenderPromise(): number {
        __S.testWhich("senderPromise", __S.getUint16(0, this), 2, this);
        return __S.getUint32(4, this);
    }
    isSenderPromise(): boolean { return __S.getUint16(0, this) === 2; }
    setSenderPromise(value: number): void {
        __S.setUint16(0, 2, this);
        __S.setUint32(4, value, this);
    }
    get senderPromise(): number { return this.getSenderPromise(); }
    set senderPromise(value: number) { this.setSenderPromise(value); }
    getReceiverHosted(): number {
        __S.testWhich("receiverHosted", __S.getUint16(0, this), 3, this);
        return __S.getUint32(4, this);
    }
    isReceiverHosted(): boolean { return __S.getUint16(0, this) === 3; }
    setReceiverHosted(value: number): void {
        __S.setUint16(0, 3, this);
        __S.setUint32(4, value, this);
    }
    get receiverHosted(): number { return this.getReceiverHosted(); }
    set receiverHosted(value: number) { this.setReceiverHosted(value); }
    adoptReceiverAnswer(value: capnp.Orphan<PromisedAnswer>): void {
        __S.setUint16(0, 4, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownReceiverAnswer(): capnp.Orphan<PromisedAnswer> { return __S.disown(this.getReceiverAnswer()); }
    getReceiverAnswer(): PromisedAnswer {
        __S.testWhich("receiverAnswer", __S.getUint16(0, this), 4, this);
        return __S.getStruct(0, PromisedAnswer, this);
    }
    hasReceiverAnswer(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initReceiverAnswer(): PromisedAnswer {
        __S.setUint16(0, 4, this);
        return __S.initStructAt(0, PromisedAnswer, this);
    }
    isReceiverAnswer(): boolean { return __S.getUint16(0, this) === 4; }
    setReceiverAnswer(value: PromisedAnswer): void {
        __S.setUint16(0, 4, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get receiverAnswer(): PromisedAnswer { return this.getReceiverAnswer(); }
    set receiverAnswer(value: PromisedAnswer | PromisedAnswer_Shape) { if (value instanceof PromisedAnswer) { this.setReceiverAnswer(value); } else { this.initReceiverAnswer().set(value); } }
    adoptThirdPartyHosted(value: capnp.Orphan<ThirdPartyCapDescriptor>): void {
        __S.setUint16(0, 5, this);
        __S.adopt(value, __S.getPointer(0, this));
    }
    disownThirdPartyHosted(): capnp.Orphan<ThirdPartyCapDescriptor> { return __S.disown(this.getThirdPartyHosted()); }
    getThirdPartyHosted(): ThirdPartyCapDescriptor {
        __S.testWhich("thirdPartyHosted", __S.getUint16(0, this), 5, this);
        return __S.getStruct(0, ThirdPartyCapDescriptor, this);
    }
    hasThirdPartyHosted(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initThirdPartyHosted(): ThirdPartyCapDescriptor {
        __S.setUint16(0, 5, this);
        return __S.initStructAt(0, ThirdPartyCapDescriptor, this);
    }
    isThirdPartyHosted(): boolean { return __S.getUint16(0, this) === 5; }
    setThirdPartyHosted(value: ThirdPartyCapDescriptor): void {
        __S.setUint16(0, 5, this);
        __S.copyFrom(value, __S.getPointer(0, this));
    }
    get thirdPartyHosted(): ThirdPartyCapDescriptor { return this.getThirdPartyHosted(); }
    set thirdPartyHosted(value: ThirdPartyCapDescriptor | ThirdPartyCapDescriptor_Shape) { if (value instanceof ThirdPartyCapDescriptor) { this.setThirdPartyHosted(value); } else { this.initThirdPartyHosted().set(value); } }
    getAttachedFd(): number { return __S.getUint8(2, this, CapDescriptor._capnp.defaultAttachedFd); }
    setAttachedFd(value: number): void { __S.setUint8(2, value, this, CapDescriptor._capnp.defaultAttachedFd); }
    get attachedFd(): number { return this.getAttachedFd(); }
    set attachedFd(value: number) { this.setAttachedFd(value); }
    set(value: CapDescriptor_Shape): void {
        if (value.none !== undefined) this.setNone();
        if (value.senderHosted !== undefined) this.setSenderHosted(value.senderHosted);
        if (value.senderPromise !== undefined) this.setSenderPromise(value.senderPromise);
        if (value.receiverHosted !== undefined) this.setReceiverHosted(value.receiverHosted);
        if (value.receiverAnswer !== undefined) this.initReceiverAnswer().set(value.receiverAnswer);
        if (value.thirdPartyHosted !== undefined) this.initThirdPartyHosted().set(value.thirdPartyHosted);
        if (value.attachedFd !== undefined) this.setAttachedFd(value.attachedFd);
    }
    get(): CapDescriptor_Json {
        return {
            ...(this.isNone() ? { none: null } : {}),
            ...(this.isSenderHosted() ? { senderHosted: this.getSenderHosted() } : {}),
            ...(this.isSenderPromise() ? { senderPromise: this.getSenderPromise() } : {}),
            ...(this.isReceiverHosted() ? { receiverHosted: this.getReceiverHosted() } : {}),
            ...(this.isReceiverAnswer() && this.hasReceiverAnswer() ? { receiverAnswer: this.getReceiverAnswer().get() } : {}),
            ...(this.isThirdPartyHosted() && this.hasThirdPartyHosted() ? { thirdPartyHosted: this.getThirdPartyHosted().get() } : {}),
            attachedFd: this.getAttachedFd(),
        };
    }
    toJSON(): CapDescriptor_Json { return this.get(); }
    toString(): string { return "CapDescriptor_" + super.toString(); }
    which(): CapDescriptor_Which { return __S.getUint16(0, this); }
}
export namespace CapDescriptor {
    export type Json = CapDescriptor_Json;
    export type Shape = CapDescriptor_Shape;
    export import Which = CapDescriptor_Which;
}
export enum PromisedAnswer_Op_Which {
    NOOP = 0,
    GET_POINTER_FIELD = 1
}
export interface PromisedAnswer_Op_Shape {
    noop?: null;
    getPointerField?: number;
}
export interface PromisedAnswer_Op_Json {
    noop?: null;
    getPointerField?: number;
}
export class PromisedAnswer_Op extends __S {
    static readonly NOOP = PromisedAnswer_Op_Which.NOOP;
    static readonly GET_POINTER_FIELD = PromisedAnswer_Op_Which.GET_POINTER_FIELD;
    static readonly _capnp = { displayName: "Op", id: "f316944415569081", size: new __O(8, 0) };
    isNoop(): boolean { return __S.getUint16(0, this) === 0; }
    setNoop(): void { __S.setUint16(0, 0, this); }
    getGetPointerField(): number {
        __S.testWhich("getPointerField", __S.getUint16(0, this), 1, this);
        return __S.getUint16(2, this);
    }
    isGetPointerField(): boolean { return __S.getUint16(0, this) === 1; }
    setGetPointerField(value: number): void {
        __S.setUint16(0, 1, this);
        __S.setUint16(2, value, this);
    }
    get getPointerField(): number { return this.getGetPointerField(); }
    set getPointerField(value: number) { this.setGetPointerField(value); }
    set(value: PromisedAnswer_Op_Shape): void {
        if (value.noop !== undefined) this.setNoop();
        if (value.getPointerField !== undefined) this.setGetPointerField(value.getPointerField);
    }
    get(): PromisedAnswer_Op_Json {
        return {
            ...(this.isNoop() ? { noop: null } : {}),
            ...(this.isGetPointerField() ? { getPointerField: this.getGetPointerField() } : {}),
        };
    }
    toJSON(): PromisedAnswer_Op_Json { return this.get(); }
    toString(): string { return "PromisedAnswer_Op_" + super.toString(); }
    which(): PromisedAnswer_Op_Which { return __S.getUint16(0, this); }
}
export namespace PromisedAnswer_Op {
    export type Json = PromisedAnswer_Op_Json;
    export type Shape = PromisedAnswer_Op_Shape;
    export import Which = PromisedAnswer_Op_Which;
}
export interface PromisedAnswer_Shape {
    questionId?: number;
    transform?: readonly PromisedAnswer_Op_Shape[];
}
export interface PromisedAnswer_Json {
    questionId: number;
    transform?: PromisedAnswer_Op_Json[];
}
export class PromisedAnswer extends __S {
    static readonly _capnp = { displayName: "PromisedAnswer", id: "d800b1d6cd6f1ca0", size: new __O(8, 1) };
    static _Transform: capnp.ListCtor<PromisedAnswer_Op>;
    getQuestionId(): number { return __S.getUint32(0, this); }
    setQuestionId(value: number): void { __S.setUint32(0, value, this); }
    get questionId(): number { return this.getQuestionId(); }
    set questionId(value: number) { this.setQuestionId(value); }
    adoptTransform(value: capnp.Orphan<capnp.List<PromisedAnswer_Op>>): void { __S.adopt(value, __S.getPointer(0, this)); }
    disownTransform(): capnp.Orphan<capnp.List<PromisedAnswer_Op>> { return __S.disown(this.getTransform()); }
    getTransform(): capnp.List<PromisedAnswer_Op> { return __S.getList(0, PromisedAnswer._Transform, this); }
    hasTransform(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initTransform(length: number): capnp.List<PromisedAnswer_Op> { return __S.initList(0, PromisedAnswer._Transform, length, this); }
    setTransform(value: capnp.List<PromisedAnswer_Op>): void { __S.copyFrom(value, __S.getPointer(0, this)); }
    get transform(): capnp.List<PromisedAnswer_Op> { return this.getTransform(); }
    set transform(value: capnp.List<PromisedAnswer_Op> | readonly PromisedAnswer_Op_Shape[]) { if (value instanceof capnp.List) { this.setTransform(value); } else { this.set({ transform: value }); } }
    set(value: PromisedAnswer_Shape): void {
        if (value.questionId !== undefined) this.setQuestionId(value.questionId);
        if (value.transform !== undefined) {
            const l = this.initTransform(value.transform.length);
            value.transform.forEach((e, i) => l.get(i).set(e));
        }
    }
    get(): PromisedAnswer_Json {
        return {
            questionId: this.getQuestionId(),
            ...(this.hasTransform() ? { transform: this.getTransform().toArray().map((e) => e.get()) } : {}),
        };
    }
    toJSON(): PromisedAnswer_Json { return this.get(); }
    toString(): string { return "PromisedAnswer_" + super.toString(); }
}
export namespace PromisedAnswer {
    export type Json = PromisedAnswer_Json;
    export import Op = PromisedAnswer_Op;
    export type Shape = PromisedAnswer_Shape;
}
export interface ThirdPartyCapDescriptor_Shape {
    vineId?: number;
}
export interface ThirdPartyCapDescriptor_Json {
    vineId: number;
}
export class ThirdPartyCapDescriptor extends __S {
    static readonly _capnp = { displayName: "ThirdPartyCapDescriptor", id: "d37007fde1f0027d", size: new __O(8, 1) };
    adoptId(value: capnp.Orphan<capnp.Pointer>): void { __S.adopt(value, __S.getPointer(0, this)); }
    disownId(): capnp.Orphan<capnp.Pointer> { return __S.disown(this.getId()); }
    getId(): capnp.Pointer { return __S.getPointer(0, this); }
    hasId(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    setId(value: capnp.Pointer): void { __S.copyFrom(value, __S.getPointer(0, this)); }
    get id(): capnp.Pointer { return this.getId(); }
    set id(value: capnp.Pointer) { this.setId(value); }
    getVineId(): number { return __S.getUint32(0, this); }
    setVineId(value: number): void { __S.setUint32(0, value, this); }
    get vineId(): number { return this.getVineId(); }
    set vineId(value: number) { this.setVineId(value); }
    set(value: ThirdPartyCapDescriptor_Shape): void {
        if (value.vineId !== undefined) this.setVineId(value.vineId);
    }
    get(): ThirdPartyCapDescriptor_Json {
        return {
            vineId: this.getVineId(),
        };
    }
    toJSON(): ThirdPartyCapDescriptor_Json { return this.get(); }
    toString(): string { return "ThirdPartyCapDescriptor_" + super.toString(); }
}
export namespace ThirdPartyCapDescriptor {
    export type Json = ThirdPartyCapDescriptor_Json;
    export type Shape = ThirdPartyCapDescriptor_Shape;
}
export enum Exception_Type {
    FAILED,
    OVERLOADED,
    DISCONNECTED,
    UNIMPLEMENTED
}
export interface Exception_Shape {
    reason?: string;
    type?: Exception_Type;
    obsoleteIsCallersFault?: boolean;
    obsoleteDurability?: number;
    trace?: string;
}
export interface Exception_Json {
    reason: string;
    type: Exception_Type;
    obsoleteIsCallersFault: boolean;
    obsoleteDurability: number;
    trace: string;
}
export class Exception extends __S {
    static readonly _capnp = { displayName: "Exception", id: "d625b7063acf691a", size: new __O(8, 2) };
    getReason(): string { return __S.getText(0, this); }
    setReason(value: string): void { __S.setText(0, value, this); }
    get reason(): string { return this.getReason(); }
    set reason(value: string) { this.setReason(value); }
    getType(): Exception_Type { return __S.getUint16(4, this); }
    setType(value: Exception_Type): void { __S.setUint16(4, value, this); }
    get type(): Exception_Type { return this.getType(); }
    set type(value: Exception_Type) { this.setType(value); }
    getObsoleteIsCallersFault(): boolean { return __S.getBit(0, this); }
    setObsoleteIsCallersFault(value: boolean): void { __S.setBit(0, value, this); }
    get obsoleteIsCallersFault(): boolean { return this.getObsoleteIsCallersFault(); }
    set obsoleteIsCallersFault(value: boolean) { this.setObsoleteIsCallersFault(value); }
    getObsoleteDurability(): number { return __S.getUint16(2, this); }
    setObsoleteDurability(value: number): void { __S.setUint16(2, value, this); }
    get obsoleteDurability(): number { return this.getObsoleteDurability(); }
    set obsoleteDurability(value: number) { this.setObsoleteDurability(value); }
    getTrace(): string { return __S.getText(1, this); }
    setTrace(value: string): void { __S.setText(1, value, this); }
    get trace(): string { return this.getTrace(); }
    set trace(value: string) { this.setTrace(value); }
    set(value: Exception_Shape): void {
        if (value.reason !== undefined) this.setReason(value.reason);
        if (value.type !== undefined) this.setType(value.type);
        if (value.obsoleteIsCallersFault !== undefined) this.setObsoleteIsCallersFault(value.obsoleteIsCallersFault);
        if (value.obsoleteDurability !== undefined) this.setObsoleteDurability(value.obsoleteDurability);
        if (value.trace !== undefined) this.setTrace(value.trace);
    }
    get(): Exception_Json {
        return {
            reason: this.getReason(),
            type: this.getType(),
            obsoleteIsCallersFault: this.getObsoleteIsCallersFault(),
            obsoleteDurability: this.getObsoleteDurability(),
            trace: this.getTrace(),
        };
    }
    toJSON(): Exception_Json { return this.get(); }
    toString(): string { return "Exception_" + super.toString(); }
}
export namespace Exception {
    export type Json = Exception_Json;
    export type Shape = Exception_Shape;
    export import Type = Exception_Type;
}
Payload._CapTable = capnp.CompositeList(CapDescriptor);
PromisedAnswer._Transform = capnp.CompositeList(PromisedAnswer_Op);
