/**
 * This file is generated by hand in order to bootstrap compiler development. It is intended to be an exact match to
 * compiled output.
 */

import * as capnp from "../index";
import { ObjectSize as __O, Struct as __S, Interface as __I } from '../index';
export const _capnpFileId = "e37ded525a68a7c9";
