/* tslint:disable */

/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */

import * as capnp from "../index";
import { ObjectSize as __O, Struct as __S } from '../index';
export const _capnpFileId = "e37ded525a68a7c9";
