/* tslint:disable */

/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */

import * as capnp from "capnp-ts";
import { ObjectSize as __O, Struct as __S } from 'capnp-ts';
export const _capnpFileId = "9cbc682922e84ff9";
export class Baz extends __S {
    static readonly _capnp = { displayName: "Baz", id: "f2f28862b8e82db7", size: new __O(0, 1) };
    getBar(): string { return __S.getText(0, this); }
    setBar(value: string): void { __S.setText(0, value, this); }
    toString(): string { return "Baz_" + super.toString(); }
}
