/* tslint:disable */

/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */

import * as capnp from "capnp-ts";
import { ObjectSize as __O, Struct as __S } from 'capnp-ts';
export const _capnpFileId = "e0b7ff464fbc7ee1";
export class Foo extends __S {
    static readonly _capnp = { displayName: "Foo", id: "9e8e6186e9348688", size: new __O(0, 1) };
    getBar(): string { return __S.getText(0, this); }
    setBar(value: string): void { __S.setText(0, value, this); }
    toString(): string { return "Foo_" + super.toString(); }
}
