"use strict";
/* eslint-disable */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.AddressBook = exports.Person = exports.Person_Employment = exports.Person_Employment_Which = exports.Person_PhoneNumber = exports.Person_PhoneNumber_Type = exports._capnpFileId = void 0;
/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
const capnp = __importStar(require("capnp-ts"));
const capnp_ts_1 = require("capnp-ts");
exports._capnpFileId = BigInt("0xef1b5abe02e1f8d4");
var Person_PhoneNumber_Type;
(function (Person_PhoneNumber_Type) {
    Person_PhoneNumber_Type[Person_PhoneNumber_Type["MOBILE"] = 0] = "MOBILE";
    Person_PhoneNumber_Type[Person_PhoneNumber_Type["HOME"] = 1] = "HOME";
    Person_PhoneNumber_Type[Person_PhoneNumber_Type["WORK"] = 2] = "WORK";
})(Person_PhoneNumber_Type || (exports.Person_PhoneNumber_Type = Person_PhoneNumber_Type = {}));
class Person_PhoneNumber extends capnp_ts_1.Struct {
    getNumber() { return capnp_ts_1.Struct.getText(0, this); }
    setNumber(value) { capnp_ts_1.Struct.setText(0, value, this); }
    get number() { return this.getNumber(); }
    set number(value) { this.setNumber(value); }
    getType() { return capnp_ts_1.Struct.getUint16(0, this); }
    setType(value) { capnp_ts_1.Struct.setUint16(0, value, this); }
    get type() { return this.getType(); }
    set type(value) { this.setType(value); }
    set(value) {
        if (value.number !== undefined)
            this.setNumber(value.number);
        if (value.type !== undefined)
            this.setType(value.type);
    }
    get() {
        return {
            number: this.getNumber(),
            type: this.getType(),
        };
    }
    toJSON() { return this.get(); }
    toString() { return "Person_PhoneNumber_" + super.toString(); }
}
exports.Person_PhoneNumber = Person_PhoneNumber;
Person_PhoneNumber._capnp = { displayName: "PhoneNumber", id: "af663da31c027e0e", size: new capnp_ts_1.ObjectSize(8, 1) };
(function (Person_PhoneNumber) {
    Person_PhoneNumber.Type = Person_PhoneNumber_Type;
})(Person_PhoneNumber || (exports.Person_PhoneNumber = Person_PhoneNumber = {}));
var Person_Employment_Which;
(function (Person_Employment_Which) {
    Person_Employment_Which[Person_Employment_Which["UNEMPLOYED"] = 0] = "UNEMPLOYED";
    Person_Employment_Which[Person_Employment_Which["EMPLOYER"] = 1] = "EMPLOYER";
    Person_Employment_Which[Person_Employment_Which["SCHOOL"] = 2] = "SCHOOL";
    Person_Employment_Which[Person_Employment_Which["SELF_EMPLOYED"] = 3] = "SELF_EMPLOYED";
})(Person_Employment_Which || (exports.Person_Employment_Which = Person_Employment_Which = {}));
class Person_Employment extends capnp_ts_1.Struct {
    isUnemployed() { return capnp_ts_1.Struct.getUint16(4, this) === 0; }
    setUnemployed() { capnp_ts_1.Struct.setUint16(4, 0, this); }
    getEmployer() {
        capnp_ts_1.Struct.testWhich("employer", capnp_ts_1.Struct.getUint16(4, this), 1, this);
        return capnp_ts_1.Struct.getText(3, this);
    }
    isEmployer() { return capnp_ts_1.Struct.getUint16(4, this) === 1; }
    setEmployer(value) {
        capnp_ts_1.Struct.setUint16(4, 1, this);
        capnp_ts_1.Struct.setText(3, value, this);
    }
    get employer() { return this.getEmployer(); }
    set employer(value) { this.setEmployer(value); }
    getSchool() {
        capnp_ts_1.Struct.testWhich("school", capnp_ts_1.Struct.getUint16(4, this), 2, this);
        return capnp_ts_1.Struct.getText(3, this);
    }
    isSchool() { return capnp_ts_1.Struct.getUint16(4, this) === 2; }
    setSchool(value) {
        capnp_ts_1.Struct.setUint16(4, 2, this);
        capnp_ts_1.Struct.setText(3, value, this);
    }
    get school() { return this.getSchool(); }
    set school(value) { this.setSchool(value); }
    isSelfEmployed() { return capnp_ts_1.Struct.getUint16(4, this) === 3; }
    setSelfEmployed() { capnp_ts_1.Struct.setUint16(4, 3, this); }
    set(value) {
        if (value.unemployed !== undefined)
            this.setUnemployed();
        if (value.employer !== undefined)
            this.setEmployer(value.employer);
        if (value.school !== undefined)
            this.setSchool(value.school);
        if (value.selfEmployed !== undefined)
            this.setSelfEmployed();
    }
    get() {
        return Object.assign(Object.assign(Object.assign(Object.assign({}, (this.isUnemployed() ? { unemployed: null } : {})), (this.isEmployer() ? { employer: this.getEmployer() } : {})), (this.isSchool() ? { school: this.getSchool() } : {})), (this.isSelfEmployed() ? { selfEmployed: null } : {}));
    }
    toJSON() { return this.get(); }
    toString() { return "Person_Employment_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(4, this); }
}
exports.Person_Employment = Person_Employment;
Person_Employment.UNEMPLOYED = Person_Employment_Which.UNEMPLOYED;
Person_Employment.EMPLOYER = Person_Employment_Which.EMPLOYER;
Person_Employment.SCHOOL = Person_Employment_Which.SCHOOL;
Person_Employment.SELF_EMPLOYED = Person_Employment_Which.SELF_EMPLOYED;
Person_Employment._capnp = { displayName: "employment", id: "e88780a90af3da0c", size: new capnp_ts_1.ObjectSize(8, 4) };
(function (Person_Employment) {
    Person_Employment.Which = Person_Employment_Which;
})(Person_Employment || (exports.Person_Employment = Person_Employment = {}));
class Person extends capnp_ts_1.Struct {
    getId() { return capnp_ts_1.Struct.getUint32(0, this); }
    setId(value) { capnp_ts_1.Struct.setUint32(0, value, this); }
    get id() { return this.getId(); }
    set id(value) { this.setId(value); }
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    get name() { return this.getName(); }
    set name(value) { this.setName(value); }
    getEmail() { return capnp_ts_1.Struct.getText(1, this); }
    setEmail(value) { capnp_ts_1.Struct.setText(1, value, this); }
    get email() { return this.getEmail(); }
    set email(value) { this.setEmail(value); }
    adoptPhones(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownPhones() { return capnp_ts_1.Struct.disown(this.getPhones()); }
    getPhones() { return capnp_ts_1.Struct.getList(2, Person._Phones, this); }
    hasPhones() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initPhones(length) { return capnp_ts_1.Struct.initList(2, Person._Phones, length, this); }
    setPhones(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    get phones() { return this.getPhones(); }
    set phones(value) { if (value instanceof capnp.List) {
        this.setPhones(value);
    }
    else {
        this.set({ phones: value });
    } }
    getEmployment() { return capnp_ts_1.Struct.getAs(Person_Employment, this); }
    initEmployment() { return capnp_ts_1.Struct.getAs(Person_Employment, this); }
    get employment() { return this.getEmployment(); }
    set employment(value) { this.initEmployment().set(value); }
    set(value) {
        if (value.id !== undefined)
            this.setId(value.id);
        if (value.name !== undefined)
            this.setName(value.name);
        if (value.email !== undefined)
            this.setEmail(value.email);
        if (value.phones !== undefined) {
            const l = this.initPhones(value.phones.length);
            value.phones.forEach((e, i) => l.get(i).set(e));
        }
        if (value.employment !== undefined)
            this.initEmployment().set(value.employment);
    }
    get() {
        return Object.assign(Object.assign({ id: this.getId(), name: this.getName(), email: this.getEmail() }, (this.hasPhones() ? { phones: this.getPhones().toArray().map((e) => e.get()) } : {})), { employment: this.getEmployment().get() });
    }
    toJSON() { return this.get(); }
    toString() { return "Person_" + super.toString(); }
}
exports.Person = Person;
Person._capnp = { displayName: "Person", id: "d94307c4985be8e7", size: new capnp_ts_1.ObjectSize(8, 4) };
(function (Person) {
    Person.Employment = Person_Employment;
    Person.PhoneNumber = Person_PhoneNumber;
})(Person || (exports.Person = Person = {}));
class AddressBook extends capnp_ts_1.Struct {
    adoptPeople(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownPeople() { return capnp_ts_1.Struct.disown(this.getPeople()); }
    getPeople() { return capnp_ts_1.Struct.getList(0, AddressBook._People, this); }
    hasPeople() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initPeople(length) { return capnp_ts_1.Struct.initList(0, AddressBook._People, length, this); }
    setPeople(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    get people() { return this.getPeople(); }
    set people(value) { if (value instanceof capnp.List) {
        this.setPeople(value);
    }
    else {
        this.set({ people: value });
    } }
    set(value) {
        if (value.people !== undefined) {
            const l = this.initPeople(value.people.length);
            value.people.forEach((e, i) => l.get(i).set(e));
        }
    }
    get() {
        return Object.assign({}, (this.hasPeople() ? { people: this.getPeople().toArray().map((e) => e.get()) } : {}));
    }
    toJSON() { return this.get(); }
    toString() { return "AddressBook_" + super.toString(); }
}
exports.AddressBook = AddressBook;
AddressBook._capnp = { displayName: "AddressBook", id: "c06ea6d038a357bb", size: new capnp_ts_1.ObjectSize(0, 1) };
Person._Phones = capnp.CompositeList(Person_PhoneNumber);
AddressBook._People = capnp.CompositeList(Person);
