/**
 * This file was **not** generated automatically. Historically it served as a template for the code generator.
 *
 * Notable differences from actual generated files are in comments below.
 *
 * @author jdiaz5513
 */

/* tslint:disable:no-use-before-declare max-classes-per-file */

// Note that this is a relative import; in an autogenerated file this would be `import * as capnp from 'capnp-ts';`.
import * as capnp from '../../lib';

export const ID = 'b597bf4897e54f89';

export class AddressBook extends capnp.Struct {

  static readonly _displayName = 'AddressBook';
  static readonly _id = 'f724540a01e98224';
  static readonly _size = new capnp.ObjectSize(0, 1);

  adoptPeople(value: capnp.Orphan<capnp.CompositeList<Person>>): void {

    this._getPointer(0).adopt(value);

  }

  disownPeople(): capnp.Orphan<capnp.CompositeList<Person>> {

    return this.getPeople().disown();

  }

  getPeople(): capnp.CompositeList<Person> {

    const list = capnp.CompositeList.fromPointer(Person, this._getPointer(0));

    if (list._isNull()) {

      list._initList(0);   // no default

    } else {

      list._validate(capnp.PointerType.LIST, capnp.ListElementSize.COMPOSITE, Person._size);

    }

    return list;

  }

  hasPeople(): boolean {

    return !this._getPointer(0)._isNull();

  }

  initPeople(length: number): capnp.CompositeList<Person> {

    const list = capnp.CompositeList.fromPointer(Person, this._getPointer(0));

    list._initList(length);

    return list;

  }

  setPeople(value: capnp.CompositeList<Person>): void {

    this._getPointer(0)._copyFrom(value);

  }

}

declare namespace Person_PhoneNumber_Type {

  export const _id = '98bef1051277b9df';

}

enum Person_PhoneNumber_Type {
  MOBILE = 0,
  HOME = 1,
  WORK = 2,
}

class Person_Employment extends capnp.Struct {

  static readonly _displayName = 'Employment';
  static readonly _id = '927f49708287c3b6';
  static readonly _size = new capnp.ObjectSize(8, 4);

  static UNEMPLOYED = 0;
  static EMPLOYER = 1;
  static SCHOOL = 2;
  static SELF_EMPLOYED = 3;

  getEmployer(): string {

    this._testWhich('employment', this.which(), 1);

    return this._getText(3);

  }

  getSchool(): string {

    this._testWhich('employment', this.which(), 2);

    return this._getText(3);

  }

  init(): void {

    this.setUnemployed();

  }

  isEmployer(): boolean {

    return this.which() === 1;

  }

  isSchool(): boolean {

    return this.which() === 2;

  }

  isSelfEmployed(): boolean {

    return this.which() === 3;

  }

  isUnemployed(): boolean {

    return this.which() === 0;

  }

  hasEmployer(): boolean {

    this._testWhich('employment', this.which(), 1);

    return !this._getPointer(3)._isNull();

  }

  hasSchool(): boolean {

    this._testWhich('employment', this.which(), 2);

    return !this._getPointer(3)._isNull();

  }

  setEmployer(value: string): void {

    this._setUint16(4, 1);
    this._setText(3, value);

  }

  setSchool(value: string): void {

    this._setUint16(4, 2);
    this._setText(3, value);

  }

  setSelfEmployed(): void {

    this._setUint16(4, 3);

  }

  setUnemployed(): void {

    this._setUint16(4, 0);

  }

  which(): number {

    return this._getUint16(4);

  }

}

class Person_PhoneNumber extends capnp.Struct {

  static readonly _displayName = 'PhoneNumber';
  static readonly _id = 'cba8ed6b45001ccc';
  static readonly _size = new capnp.ObjectSize(2, 1);

  static readonly Type = Person_PhoneNumber_Type;

  getNumber(): string {

    return this._getText(0);

  }

  getType(): Person_PhoneNumber_Type {

    return this._getUint16(0);

  }

  setNumber(value: string): void {

    this._setText(0, value);

  }

  setType(value: Person_PhoneNumber_Type): void {

    this._setUint16(0, value);

  }

}

export class Person extends capnp.Struct {

  static readonly _displayName = 'Person';
  static readonly _id = 'efbbc4e996f07104';
  static readonly _size = new capnp.ObjectSize(8, 4);

  static readonly Employment = Person_Employment;
  static readonly PhoneNumber = Person_PhoneNumber;

  adoptPhones(value: capnp.Orphan<capnp.CompositeList<Person_PhoneNumber>>): void {

    this._getPointer(2).adopt(value);

  }

  disownPhones(): capnp.Orphan<capnp.CompositeList<Person_PhoneNumber>> {

    return this.getPhones().disown();

  }

  getEmail(): string {

    return this._getText(1);

  }

  getEmployment(): Person_Employment {

    return this._getAs(Person_Employment);

  }

  getId(): number {

    return this._getUint32(0);

  }

  getName(): string {

    return this._getText(0);

  }

  getPhones(): capnp.CompositeList<Person_PhoneNumber> {

    const list = capnp.CompositeList.fromPointer(Person_PhoneNumber, this._getPointer(2));

    if (list._isNull()) {

      list._initList(0);

    } else {

      list._validate(capnp.PointerType.LIST, capnp.ListElementSize.COMPOSITE, Person_PhoneNumber._size);

    }

    return list;

  }

  hasEmail(): boolean {

    return !this._getPointer(1)._isNull();

  }

  hasName(): boolean {

    return !this._getPointer(0)._isNull();

  }

  hasPhones(): boolean {

    return !this._getPointer(2)._isNull();

  }

  initEmployment(): Person_Employment {

    const e = this.getEmployment();
    e.init();

    return e;

  }

  initPhones(length: number): capnp.CompositeList<Person_PhoneNumber> {

    const list = capnp.CompositeList.fromPointer(Person_PhoneNumber, this._getPointer(2));

    list._initList(length);

    return list;

  }

  setEmail(value: string): void {

    this._setText(1, value);

  }

  setId(value: number): void {

    this._setUint32(0, value);

  }

  setName(value: string): void {

    this._setText(0, value);

  }

  setPhones(value: capnp.CompositeList<Person_PhoneNumber>): void {

    this._getPointer(2)._copyFrom(value);

  }

}
